// Canonical character lore supplied for the Hero Codex and Meet the Characters.
// Headings/titles from the source are intentionally omitted from the UI.
export const CHARACTER_LORE = {
  'Thunder Hero': 'The first and greatest of the five ancient Element 6 awakenings, the Thunder Hero was only sixteen when lightning first began obeying him during a storm. His power quickly became legendary, and he joined four other awakened warriors—Fire, Water, Grass, and Ice—to defend villages and eventually challenge the warlords dividing the continent. Together they fought the Hundred Blade War, a conflict that would have lasted decades without them. He split a mountain to rescue 12,000 trapped civilians, never lost a recorded duel, and became the unquestioned leader of the five. After the war, he remained for centuries, eventually training successors before disappearing into legend.',
  'Fire Hero': 'The Fire Hero awakened when a monk desperately tried to keep his brothers warm during a deadly mountain blizzard, causing a dying fire to grow without fuel. He became the most aggressive member of the original five, mastering fire powerful enough to annihilate enemy formations and burn through castle defenses. During the Hundred Blade War, he repeatedly fought on the front lines and became famous for arriving wherever battles were at their worst. After peace returned, he abandoned warfare and returned to monastic life, training generations of students and preserving knowledge that would eventually influence later Elementors.',
  'Water Hero': 'The Water Hero awakened while drowning in a flooded river, only for the water itself to carry her safely against the current. She became one of the greatest rescuers of the Hundred Blade War, using water to disable armies while avoiding unnecessary deaths. She saved countless civilians, protected coastal settlements from disasters unrelated to the war, and helped defeat Kessho\'s army at the mountain pass. After the war, she settled near the coast and spent decades preventing disasters before they happened, becoming the model later Water Elementors would follow.',
  'Grass Hero': 'The Grass Hero awakened after being buried alive in a landslide and surviving for six days while vines grew toward his hands. He became the calmest member of the original five, manipulating vegetation and earth to create barriers, protect settlements, and reshape battlefields. During the Hundred Blade War, he repeatedly stopped cavalry charges and protected civilians while mediating between the group\'s more aggressive members. His greatest achievement came after the war, when he transformed an entire mountain range into a protected forest that survived for centuries.',
  'Ice Hero': 'The Ice Hero awakened after surviving a northern storm that should have killed him, emerging from the snow completely unharmed and permanently connected to the cold. He became the silent defender of the original five, appearing whenever battles threatened to become massacres and freezing entire areas to control the fighting. He helped defeat Kessho and repeatedly protected the group during the Hundred Blade War. After the Long Peace began, he disappeared into the far north and was never confirmed dead or alive.',
  'Renji': 'Renji grew into the natural leader of the second generation, carrying the legacy of the Thunder Hero while developing a fighting style centered on hardened physical strikes. He helped uncover the conspiracy behind the rogue Elementors, survived the Twin Foxes\' assassination attempt, and defeated Ittō during the siege of the Eastern Castle without killing him. He led the eight through the Great Yokai Hunt and the war against Utsuro, eventually fighting Utsuro\'s central form alongside Kaito. After Utsuro\'s destruction, Renji became one of the principal leaders of the new Corps.',
  'Kaito': 'Kaito was one of Generation II\'s strongest offensive fighters, wielding powerful fire but initially relying too heavily on aggression. His recklessness nearly cost him his life against Ittō, and his impatience repeatedly put him at odds with Renji\'s caution. Over time, however, he learned to combine speed with discipline. He fought in the Eastern Castle siege, helped defeat multiple yokai, and eventually fought Utsuro beside Renji in perfect coordination. After the war, Kaito trained alongside Ittō, turning a former enemy into one of his closest rivals.',
  'Hana': 'Hana became Generation II\'s water wielder and one of its most dependable protectors. She helped uncover the strange Element 6 harvesting operation beneath the forgotten temple and repeatedly used her abilities for rescue rather than destruction. During the Eastern Castle siege, she flooded the fortress\'s moat approaches, and during the final war she redirected Utsuro\'s unstable energy before it could destroy the chamber. After the war, Hana returned to the coast and continued protecting communities from disasters, following the legacy of the original Water Hero.',
  'Daigo': 'Daigo was Generation II\'s defensive powerhouse, using earth and stone to create barriers strong enough to protect the others. He helped bring down the Eastern Castle\'s defenses, developed the technique that allowed the Corps to safely sever the Puppeteer\'s threads, and repeatedly held defensive lines that others could not. During the Amayo Fields battle, he held a collapsing line against an enemy force three times his size and survived. He nearly died fighting Utsuro\'s oni, but continued fighting afterward and later rebuilt villages alongside Old Tetsu.',
  'Suzu': 'Suzu became the Corps\' fastest scout and one of its most important intelligence gatherers. She discovered the first village enslaved by the Puppeteer after accidentally following a runaway horse, exposing the scale of the threat. She spent the war carrying messages, scouting enemy positions, and supporting flanking operations. During the Amayo Fields battle she suffered severe damage to one side of her body but survived because of Yui\'s healing. After the war, she continued visiting Osamu and remained connected to the Corps.',
  'Mai': 'Mai was Generation II\'s shadow specialist, known for infiltration and fighting where others could not reach. She helped expose the Twin Foxes\' illusions and later entered Utsuro\'s shadow directly, becoming the only member of the Corps to experience the entity from within. There she discovered that Utsuro was composed of hundreds of stolen fragments rather than being a single being. She used that knowledge during the final battle, helping Yui understand how Utsuro could be restored. Afterward, Mai remained beside Renji as one of the Corps\' leaders.',
  'Osamu': 'Osamu was the oldest of the eight and the member who remembered what warfare was like before Element 6. His sound-based abilities allowed him to disorient entire companies of soldiers and control battlefields without directly destroying them. He was crucial during the Eastern Castle siege and later became the Corps\' most experienced strategist. During the final battle with Utsuro, he held a collapsing entrance against an entire wave of hollowed soldiers, suffering a permanent injury that ended his fighting career. He later trained the next generation at the Ashen Monastery.',
  'Yui': 'Yui was Generation II\'s healer and one of the quietest members of the Corps, but eventually became essential to defeating Utsuro. She healed Suzu after a devastating hollowing attack and supported the team through the Amayo Fields battle. During the final confrontation, she realized that Utsuro could not simply be destroyed without losing the stolen Element 6 inside it. Instead, she restored the stolen fragments one by one, causing hundreds of pieces to return toward their original owners and peacefully ending Utsuro. She continued healing long after the war.',
  'Takeshi': 'Takeshi was one of the most important leaders of the age before the modern Hero Corps. He helped organize the Assembly and later played a major role in establishing the Grand Tournament and the political structure surrounding Elementors. Decades later, despite being retired from leadership, he helped establish the modern Corps\' identity and pushed for the simple color-based names that would define future generations. His greatest achievement was preserving the idea that Elementors should serve people rather than rule them.',
  'Aiko': 'Aiko was a warrior of the Fallen Age who became known for her willingness to confront rogue Elementors directly. She was formally censured after killing one of them, but refused to abandon the people she believed needed protection. Her actions helped establish the difficult balance between justice and restraint that later generations of Elementors would struggle with.',
  'Haru': 'Haru was one of the Fallen Age Elementors whose abilities made him valuable during the unstable period surrounding the Assembly. He fought alongside the developing network of warriors that would eventually influence Generation II and the modern Corps. His legacy survived primarily through the battles and organizations of the era rather than through a single legendary victory.',
  'Chiyo': 'Chiyo was a Fallen Age fighter whose abilities made her particularly dangerous in close combat. She became part of the generation that fought during the period when rogue Elementors and political factions were increasingly using Element 6 as a weapon. Her career helped establish the experience that later generations inherited when the larger conflicts surrounding the Harvest Guild began.',
  'Emi': 'Emi possessed an ability connected to blood and became useful in tracking and identifying threats during the Fallen Age. She operated during an era when Element 6 users were becoming increasingly entangled with political factions and secret research. Her work contributed to the growing understanding that Element 6 could be manipulated, extracted, and weaponized.',
  'Nozomi': 'Nozomi became known for dealing with Blight, one of the major dangers of the Fallen Age. Her work focused less on conventional battles and more on containment, making her one of the people responsible for preventing the Blight from spreading beyond controlled areas.',
  'Masaru': 'Masaru was hardened by the Blight after it claimed his parents, turning him into one of its most relentless opponents. He became an aggressive fighter who specialized in confronting infected threats directly. His personal loss made him one of the generation\'s most determined warriors.',
  'Ryo': 'Ryo specialized in infiltration and investigation, using mist-based abilities to move through dangerous areas without being detected. His work helped the Assembly gather information during a period when political conspiracies and rogue Elementors were becoming increasingly difficult to distinguish from one another.',
  'Souta': 'Souta was one of the younger fighters of the Fallen Age, developing ash-based abilities while surrounded by the growing instability of Element 6. Though younger and less experienced than the Assembly\'s veterans, he became part of the generation that carried the fight forward into the next era.',
  'Ogata': 'Ogata was a physician and researcher whose work became one of the darkest legacies of the Fallen Age. His research into Element 6 extraction eventually became the foundation for the Harvest Guild\'s experiments, allowing power to be removed from awakened individuals and concentrated artificially. His research would ultimately contribute to the creation of rogue Elementors and the centuries-long harvesting operation discovered by Generation II.',
  'Lord Kanenobu': 'Lord Kanenobu was a powerful daimyo whose political influence helped shape the fractured world of the Fallen Age. Rather than being remembered solely as a warrior, his importance came from the political and economic forces surrounding Element 6. His era helped establish the rivalries between clans and factions that later generations would inherit.',
  'Cobalt': 'Cobalt, originally Kenji Aoyama, became the natural leader of the fourth generation. His Element 6 created dense blue-shimmering barriers capable of stopping almost anything, making him the Corps\' primary defender. He helped establish the modern Hero Corps and later led it through the Harvest Guild crisis, the loss of several teammates\' powers, and the Controller\'s attacks. Even after losing members of his generation to extraction, he kept the organization functioning and accepted technology as a replacement for lost abilities.',
  'Cyan': 'Cyan, originally Reiji Fuma, was the wind-wielding member of the founding Corps. His ability gave the team mobility and aerial control while complementing Cobalt\'s defensive abilities. He helped establish the early Hero Corps during its first major conflicts and became one of the original symbols of the organization.',
  'Onyx': 'Onyx, originally Ayaka Kurosawa, was the Corps\' shadow specialist and one of its best infiltrators. She was the first founder to encounter the mysterious Controller personally and managed to get closer to him than almost anyone else. Her investigation revealed his prosthetic arm and his connection to the Harvest Guild, even though he escaped before she could capture him.',
  'Gold': 'Gold, originally Sora Kanade, was the youngest founder and possessed restorative abilities connected to her warm golden energy. During the siege of the Corps\' unfinished headquarters, she spent hours moving between wounded teammates and keeping them alive. She later rescued a child named Sota from beneath the ruins of an apartment building, an event that became one of the defining moments of her career.',
  'Vermilion': 'Vermilion, originally Haruto Ban, awakened with fire beneath his skin and became one of the Corps\' main offensive fighters. During the Harvest Guild crisis, he was one of the first heroes to have his Element 6 extracted, leaving him powerless. Rather than retire, he fought with Daichi\'s resonance technology and helped defend the Corps headquarters, proving that his heroism was not dependent on his powers.',
  'Umber': 'Umber, originally Yumi Sato, possessed tremor-sensing abilities that allowed her to detect movement through the ground before others could. She lost her Element 6 to the Harvest Guild but continued fighting using martial arts and Daichi\'s resonance equipment. Even without her original power, she helped defend the Corps\' tower and became an example of how skill could survive after an awakening was taken away.',
  'Graphite': 'Graphite, originally Chika Enomoto, could read the resonance of locations and detect traces of Element 6 that others could not perceive. Her ability helped the Corps investigate the Harvest Guild and identify the unnatural residue surrounding its research. She also helped recognize the pattern behind the mysterious man manipulating events from the shadows, eventually contributing to the name The Controller.',
  'Daichi Ishii': 'Daichi never awakened an Element 6 ability. Instead, he came from the Ishii-Tetsu family, a three-generation line of blacksmiths who specialized in forging weapons and equipment capable of resonating with Element 6. When Vermilion and Umber lost their powers, Daichi created resonance-calibrated gauntlets, barrier plating, and communications technology that allowed powerless heroes to continue fighting. His greatest contribution was proving that the Corps needed more than superpowers to survive.',
  'Renko Kurenai': 'Renko came from a disgraced noble family determined to reclaim its former influence. She became the leader of the Harvest Guild, also known as the Kurenai Ring, and rebuilt Ogata\'s forbidden research into an operation capable of extracting Element 6 from awakened people. Her organization successfully stole the powers of Vermilion and Umber before the Corps captured her, but her research ultimately revealed that something much older had been guiding the entire operation.',
  'Yellow': 'Yellow awakened after pushing himself beyond normal human speed on a track, collapsing as his muscles began glowing gold. His ability enhances his own physical performance and can strengthen the endurance of allies. He became one of the Corps\' most reliable support fighters, repeatedly keeping teammates alive through extreme battles. During the Controller and Evil wars, he sustained his enhancement beyond normal limits, even helping Maroon survive impossible energy overloads.',
  'Blue': 'Blue awakened after falling into a storm-lashed lake and discovering that the water itself would rise, freeze, and obey him. He became one of the Corps\' strongest environmental fighters, manipulating water and ice to protect civilians and control disasters. He froze tidal surges during the Controller War, fought Snodvor\'s overwhelming ice, and later froze spreading nothingness during the battle against Evil. After the wars, he restored damaged coral reefs.',
  'Purple': 'Purple awakened with powerful shadow-based abilities, becoming one of the Corps\' most effective infiltrators and assassins of enemy positions. He repeatedly dismantled hostile Elementor units, coordinated aerial attacks with White, helped secure captured villains, and fought inside the Controller\'s distorted nexus. During the final wars, his ability to strike from unexpected angles made him especially valuable against enemies who could manipulate conventional battlefields.',
  'Orange': 'Orange developed the ability to create portals, turning him into the Corps\' primary rapid-response specialist. His portals allowed heroes and civilians to cross enormous distances almost instantly, and he became essential during large-scale disasters. During the Controller War he created stable portal anchors inside unstable space, while during the Evil War he kept portals open through collapsing dimensions.',
  'Green': 'Green awakened when a group of bullies cornered him and his emotional reaction caused the ground beneath him to erupt into a stone shield. He became the Corps\' terrain specialist, reinforcing buildings, reshaping battlefields, and creating massive defensive structures. He helped stabilize the Split City, reinforced collapsing foundations, and eventually raised entire continents as shields during Evil\'s attack on reality itself.',
  'Pink': 'Pink awakened when fear caused her telekinesis to explode outward, lifting and twisting crates around her. She became one of the most powerful raw Elementors in the Corps but struggled with feeling treated as a weapon rather than a person. The Controller manipulated those insecurities and temporarily turned her against the Corps. She was eventually rescued without being killed, returned to the team, and later helped defeat the Controller by matching his power directly.',
  'Grey': 'Grey specialized in creating powerful force barriers and became one of the Corps\' main defensive specialists. He protected teammates during the Harvest Guild crisis, repeatedly shielded civilians during city-wide disasters, and held defensive positions against the Controller\'s overwhelming energy. During the Evil War, his barriers were pushed beyond normal combat and used to reinforce reality itself.',
  'Turquoise': 'Turquoise possessed shapeshifting abilities that made infiltration almost impossible to counter. He could mimic enemy forms and infiltrate hostile Elementor groups, making him invaluable for intelligence operations. During the Controller War he used enemy-like forms to confuse the Controller\'s projections, while during the Evil War he adapted himself into anti-forms capable of countering reality-warping distortions.',
  'Olive': 'Olive could alter his size, allowing him to change the scale of himself and objects around him. His unusual ability became unexpectedly powerful against enemies whose techniques depended on normal-sized battlefields. He defeated Temple by shrinking the battlefield around him, and later used his power to resize dangerous debris and even singularities during the Controller and Evil wars.',
  'Copper': 'Copper developed an ability to freeze extremely short periods of time, first experimenting by stopping falling dust in midair. His power eventually became essential for rescuing civilians during collapsing structures and unstable reality. He froze microseconds during the Controller War and even stopped portions of collapsing time itself during the final battle against Evil.',
  'Emerald': 'Emerald could phase through solid matter, allowing him to pass through walls and evade attacks. During a training exercise, however, Crimson\'s uncontrolled blast caught him while he was transitioning between solid and intangible states, killing him. His death became one of Crimson\'s greatest regrets and helped drive Crimson toward mastering control. Emerald was later absent from the Corps\' major wars, his loss remaining a permanent reminder of the danger of uncontrolled Element 6.',
  'Pearl': 'Pearl relied on extraordinary sound perception rather than conventional sight, allowing her to sense people and movements around her. She guided teammates through smoke, called enemy movements before they happened, and helped the Corps navigate areas where normal senses failed. During the Evil War, she continued fighting despite the loss of ordinary sensory information caused by reality itself beginning to disappear.',
  'Red': 'Red\'s fire awakened from grief and became one of the Corps\' strongest offensive powers. He fought Kirsten during the stadium attack, later fought alongside Crimson during the Controller War, and burned through containment barriers and energy constructs. After Crimson\'s death, Red carried the emotional weight of his sacrifice, eventually mastering his fire enough to teach controlled flame to children. He later rejected immortality, choosing to continue living naturally.',
  'Lavender': 'Lavender could create platforms and barriers from hardened air. She became essential to aerial combat and evacuation, repeatedly creating temporary bridges and safe paths during disasters. She helped evacuate civilians during the stadium attack, supported the Corps during the Controller War, and eventually hardened even the vacuum of space into barriers during Evil\'s assault on reality.',
  'Amber': 'Amber possessed the ability to create physical duplicates of herself. She was present during the Corps\' earliest training and proved useful for overwhelming opponents and confusing enemies. Her most important achievement came during the early generation\'s battles, where she fought alongside the other colors. She was later lost before the Controller War, and her absence was specifically felt when the remaining Corps fought the Split City battle.',
  'Black': 'Black awakened when lightning struck him and, instead of harming him, bent around his body and waited for his command. He became one of the Corps\' most powerful fighters and eventually its only immortal member. He destroyed Cable\'s lightning circuit during the stadium attack, anchored reality with thunder during the Evil War, and helped contain Evil itself. After accepting eternal life from Life, Black remained as an immortal protector for millions of years, eventually continuing his career as a strangely ordinary city protector.',
  'Maroon': 'Maroon possessed the ability to absorb electrical and other forms of energy, making him the Corps\' living energy reservoir. He absorbed enormous attacks during the Controller War and pushed his body to the point of bleeding from the overload. During the Evil War, he absorbed impossible amounts of anti-energy while Yellow sustained his body. His ability became one of the few defenses capable of surviving Evil\'s attacks on reality.',
  'Magenta': 'Magenta possessed adhesive energy capable of binding objects, structures, and eventually even unstable reality itself. She repeatedly saved teammates by sealing ruptures and holding collapsing structures together. During the Controller\'s final battle, she sacrificed herself by creating a massive binding web around his catastrophic blast, preventing the explosion from killing the rest of the Corps. Her death became one of the defining sacrifices of the Controller War.',
  'Scarlet': 'Scarlet awakened in a cemetery while grieving, discovering that she could sense the lingering energy surrounding death. Rather than simply controlling the dead, she became especially sensitive to life and death energy. She helped neutralize death-energy surges, redirected life echoes during the Controller War, and later used that ability against Evil when reality itself began losing its connection to life.',
  'Indigo': 'Indigo was the first modern awakening shown in the lore, lifting her crib through telekinetic gravitational distortion while still a child. Her power developed into complete control over gravity, eventually making her the strongest strategic leader in the Corps. She became leader after Silver stepped down, stabilized entire cities, fought the Controller in distorted space, and expanded gravity wells to prevent Evil from erasing reality. She ultimately helped contain Evil and became one of the central figures of the new era.',
  'Silver': 'Silver awakened when his hand transformed into metal, but his true gift eventually revealed itself as foresight. He founded the modern Hero Corps, recruited its first members, and became its original leader. His predictions repeatedly saved the team, including during the Controller\'s final battle. After realizing that his leadership was becoming control rather than trust, he gave command to Indigo. During Evil\'s attack, Silver sacrificed himself by taking the annihilation surge meant for the next generation. He was later resurrected and returned to the Corps.',
  'Crimson': 'Crimson was the Corps\' strongest raw attacker, possessing incredibly dense and unstable destructive energy capable of cracking reinforced steel. His greatest weakness was his lack of control, which caused the death of Emerald during training. He eventually transformed that failure into discipline. During the Controller War, he deliberately compressed his power inward and sacrificed himself to destroy an amplification node that could have destabilized half a continent. His sacrifice proved that the reckless Crimson had finally mastered his greatest weakness. He was later resurrected.',
  'Kirsten': 'Kirsten was an extremely skilled fire wielder who attacked the Hero Corps alongside Snodvor, Cable, and Volt during a public exhibition. Her fire was precise and highly controlled, allowing her to match Red blow for blow despite his own considerable power. She and Snodvor used Cable\'s lightning circuit to amplify their abilities, nearly destroying the stadium. Once the circuit was broken, Pink restrained them and Purple secured Kirsten.',
  'Volt': 'Volt was one of the four coordinated attackers at the exhibition stadium. His ability centered on devastating concussive sound, powerful enough to knock civilians to the ground and crack the stadium\'s reinforced glass roof. During the battle, Indigo used gravity to pin him down and prevent him from generating another massive pulse, allowing the Corps to finally defeat the coordinated attack.',
  'Temple': 'Temple became known as the Master of Dismantle because his ability could break down structures and defenses simply by interacting with them. Conventional attacks were almost useless against him, as barriers crumbled and physical strikes could fail to connect. Olive ultimately defeated him by shrinking the entire battlefield, making Temple\'s normal-scale dismantling ability ineffective long enough for Maroon to absorb the unstable energy surrounding him.',
  'Nightmare': 'Nightmare was a mental threat rather than a conventional physical enemy, trapping victims inside waking nightmares and using their own minds against them. He successfully trapped Yellow inside a mental prison until Pink entered the psychic environment and rescued him. The encounter demonstrated that the Corps could be threatened even when their physical powers were useless.',
  'Hazel': 'Hazel was a poison-based Elementor who transformed gardens into lethal environments filled with venomous plants and thorned vines. She worked with Whami to create an ever-changing poison garden that adapted to the Corps\' attacks. Her plants could release corrosive spores and toxic substances capable of changing the battlefield itself. The Corps eventually defeated the pair by recognizing that their strategy depended on constant adaptation.',
  'Whami': 'Whami was Hazel\'s partner and an alchemist capable of creating and modifying powerful toxins during combat. His greatest strength was adaptation: whenever the Corps developed a countermeasure, he altered the poison into something new. Together with Hazel, he transformed an entire community garden district into a constantly changing battlefield until the Corps recognized how his reactive chemistry worked.',
  'The Puppeteer': 'The Puppeteer, also known as Nishikawa, manifested Element 6 as living threads capable of controlling entire villages. His victims moved through daily life without realizing they were being controlled, making him one of the most disturbing rogue Elementors encountered by Generation II. The Corps eventually freed three villages, with Daigo developing the technique necessary to cut the threads without killing the victims. The Puppeteer escaped underground, becoming one of the first major clues pointing toward the larger harvesting conspiracy.',
  'Hollow Monk': 'The Hollow Monk, Ibuki, was once a healer who twisted his abilities into a form of life-draining and life-transfer. He believed restoration always required a cost and became convinced that he was simply using Element 6 honestly. Yui confronted him after discovering the consequences of his methods, but he escaped. Years later, he temporarily allied with the Corps during the war against Utsuro, using his twisted restoration techniques against the entity\'s draining abilities.',
  'Ittō': 'Ittō was a rogue swordsman whose blade had been unnaturally enhanced with Element 6, allowing it to cut through Daigo\'s stone defenses. He initially served powerful patrons, including the warlord Hidetaka, and helped enforce control over multiple provinces. Renji eventually defeated him in single combat during the Eastern Castle siege but spared his life. Ittō later abandoned Hidetaka and eventually returned to fight beside the Corps against Utsuro. After the war, he became a frequent training partner and rival to Kaito.',
  'The Twin Foxes': 'Reiko and Ren were illusion-based assassins hired to eliminate members of the Corps one by one. Their illusions nearly caused Kaito to kill Renji, threatening to destroy the team\'s trust before it had properly formed. They disappeared after the failed contract, but later returned during Utsuro\'s war after discovering that their own mysterious employer had been consumed by the same entity they had unknowingly served. They became intelligence agents for the Corps, using their knowledge of enemy movements to help win the Battle of Amayo Fields.',
  'Utsuro': 'Utsuro was an ancient corrupted remnant created from fragments of Element 6 stolen from hundreds of people over roughly three centuries. It spent generations harvesting awakened power, creating rogue Elementors, destabilizing Element 6, and turning people into hollowed servants. Generation II eventually discovered its forgotten temple and traced the entire conspiracy back to it. During the final battle, Yui restored the stolen fragments instead of destroying them, causing Utsuro to peacefully break apart and release everything it had taken.',
  'The Controller': 'The Controller was the mastermind manipulating the modern rogue Elementor crisis from behind the scenes. He funded and guided the Harvest Guild, manipulated Pink\'s insecurities, coordinated Elementor uprisings, and eventually built an amplification network capable of destabilizing an entire continent. He could absorb, redirect, and multiply Element 6 energy, making conventional attacks increasingly ineffective. After Crimson\'s sacrifice weakened his infrastructure and Magenta sacrificed herself protecting the team, the entire Corps combined their powers to destroy his energy nexus and defeat him.',
  'Evil': 'Evil existed beyond ordinary Element 6 and represented the force of opposition and imbalance. Unlike the Controller, Evil did not simply attack with energy—it erased portions of existence itself. During the final cosmic war, he nearly destroyed reality, forcing the entire Corps to fight across fractured space. Silver sacrificed himself protecting the future generation, while the remaining heroes combined their abilities with Life, Mercy, and Death to contain Evil. He was not destroyed; he was imprisoned, restoring balance to existence.',
  'Life': 'Life was one of the fundamental cosmic forces connected to the origin of Element 6. After the final battle against Evil, Life helped restore the balance of existence and offered the surviving heroes eternal life. Only Black accepted, choosing to become an immortal protector. Life also helped restore those who had fallen during the war, including Silver and Crimson, allowing the surviving heroes to continue into the peaceful era that followed.',
  'Death': 'Death represented the natural boundary of existence and was one of the cosmic forces involved in maintaining balance. During Evil\'s assault, Death itself trembled as reality began to disappear. When the Corps finally fractured Evil, Death closed the resulting rupture and prevented the destruction from spreading further. Afterward, Death remained alongside Life and Mercy, continuing to exist as part of the restored balance.',
  'Mercy': 'Mercy was the third cosmic force responsible for restoring equilibrium after Evil\'s defeat. While Life restored what had been damaged and Death closed the rupture, Mercy stabilized the transition between destruction and restoration. Mercy remained after the final war alongside Life and Death, watching over the peaceful universe that emerged after Evil was contained.',
  'Magneto': 'The lore file does not currently give Magneto a documented origin or major achievements, so I don\'t want to invent one and accidentally make something non-canon. His roster appearance confirms him as a character, but the provided lore doesn\'t yet establish his backstory.',
  'Willow': 'Like Magneto, Willow appears on the roster, but the current lore file does not provide enough documented history to give him/her a genuine full-origin biography without making things up.',
  'Cable': 'Cable was one of the four villains who attacked the exhibition stadium alongside Kirsten, Snodvor, and Volt. His lightning did not simply strike normally—it formed a chain between Kirsten\'s fire and Snodvor\'s ice, continuously amplifying both of them. Black specifically targeted Cable and overwhelmed the lightning circuit, breaking the connection and weakening the other two villains enough for the Corps to defeat them.',
  'Snodvor': 'Snodvor was an extraordinarily powerful ice wielder who attacked the Hero Corps during the stadium exhibition with Kirsten, Cable, and Volt. His cold was powerful enough to overpower Blue\'s own ice, covering an entire section of the stadium in a massive blizzard. Cable\'s lightning amplified his abilities by linking his ice with Kirsten\'s fire, but once Black destroyed the circuit, Pink pinned Snodvor down alongside Kirsten and the Corps captured the attackers.',
};

function normalizeLoreKey(value) {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\bhero\b/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

const NORMALIZED_LORE = Object.fromEntries(
  Object.entries(CHARACTER_LORE).map(([name, lore]) => [normalizeLoreKey(name), lore])
);

export function getCanonicalLore(char) {
  if (!char) return '';
  const direct = CHARACTER_LORE[char.name];
  if (direct) return direct;
  const normalized = normalizeLoreKey(char.name);
  if (NORMALIZED_LORE[normalized]) return NORMALIZED_LORE[normalized];
  if (char.fullName && NORMALIZED_LORE[normalizeLoreKey(char.fullName)]) {
    return NORMALIZED_LORE[normalizeLoreKey(char.fullName)];
  }
  return char.lore || '';
}
