// Down Heavy attacks — unique per character, different from their side heavy (heavyAttack)
export const DOWN_HEAVIES = {
  yellow: { name: 'Golden Stomp', desc: 'Enhanced ground stomp with golden shockwave', damage: 25, range: 130, duration: 24, color: '#FFD700', type: 'groundSlam', knockback: 1.5 },
  blue: { name: 'Ice Slam', desc: 'Slams trident down freezing the ground', damage: 22, range: 140, duration: 26, color: '#AADDFF', type: 'freeze', knockback: 1.3 },
  purple: { name: 'Shadow Crush', desc: 'Vanishes and slams down from above', damage: 26, range: 125, duration: 22, color: '#9944CC', type: 'teleSlash', knockback: 1.4 },
  orange: { name: 'Portal Drop', desc: 'Drops a boulder through a portal', damage: 24, range: 135, duration: 25, color: '#FF8800', type: 'portalStrike', knockback: 1.3 },
  green: { name: 'Mountain Stomp', desc: 'Slams hammer creating stone pillars', damage: 28, range: 145, duration: 28, color: '#44AA44', type: 'groundSlam', knockback: 1.6 },
  pink: { name: 'TK Slam', desc: 'Lifts opponent and slams them down', damage: 23, range: 130, duration: 24, color: '#FF66AA', type: 'voidDrop', knockback: 1.4 },
  grey: { name: 'Wall Drop', desc: 'Creates a wall and slams it down', damage: 25, range: 135, duration: 26, color: '#888888', type: 'groundSlam', knockback: 1.5 },
  turquoise: { name: 'Beast Stomp', desc: 'Transforms and stomps with beast force', damage: 26, range: 130, duration: 25, color: '#44CCAA', type: 'groundSlam', knockback: 1.5 },
  olive: { name: 'Titan Slam', desc: 'Grows massive and slams down', damage: 27, range: 150, duration: 28, color: '#808000', type: 'groundSlam', knockback: 1.6 },
  copper: { name: 'Time Stomp', desc: 'Freezes time on impact', damage: 24, range: 135, duration: 26, color: '#CC7744', type: 'freeze', knockback: 1.4 },
  emerald: { name: 'Phase Slam', desc: 'Phases through ground and erupts', damage: 23, range: 130, duration: 24, color: '#33CC66', type: 'riftUp', knockback: 1.3 },
  pearl: { name: 'Echo Slam', desc: 'Sound wave slams the ground', damage: 22, range: 140, duration: 25, color: '#EEEEDD', type: 'groundSlam', knockback: 1.4 },
  red: { name: 'Inferno Slam', desc: 'Slams down creating fire eruption', damage: 26, range: 135, duration: 26, color: '#FF3333', type: 'groundSlam', knockback: 1.5 },
  lavender: { name: 'Air Slam', desc: 'Solidifies air into a hammer', damage: 24, range: 130, duration: 25, color: '#BB88DD', type: 'groundSlam', knockback: 1.4 },
  amber: { name: 'Clone Slam', desc: 'Multiple clones slam simultaneously', damage: 25, range: 140, duration: 26, color: '#FFBB33', type: 'groundSlam', knockback: 1.5 },
  black: { name: 'Thunder Slam', desc: 'Lightning strikes on impact', damage: 27, range: 135, duration: 26, color: '#FFFF44', type: 'groundSlam', knockback: 1.5 },
  magenta: { name: 'Glue Slam', desc: 'Slams creating sticky trap', damage: 22, range: 130, duration: 26, color: '#FF44AA', type: 'freeze', knockback: 1.3 },
  indigo: { name: 'Gravity Slam', desc: 'Slams with intensified gravity', damage: 25, range: 140, duration: 26, color: '#4B0082', type: 'groundSlam', knockback: 1.5 },
  maroon: { name: 'Energy Slam', desc: 'Slams with concentrated energy', damage: 28, range: 135, duration: 27, color: '#800000', type: 'groundSlam', knockback: 1.6 },
  crimson: { name: 'Crimson Slam', desc: 'Construct blade slams the ground', damage: 26, range: 140, duration: 26, color: '#DC143C', type: 'groundSlam', knockback: 1.5 },
  scarlet: { name: 'Death Slam', desc: 'Necromantic energy erupts', damage: 25, range: 135, duration: 26, color: '#FF2400', type: 'groundSlam', knockback: 1.4 },
  white: { name: 'Heaven Slam', desc: 'Descends with holy force', damage: 26, range: 140, duration: 26, color: '#EEEEEE', type: 'groundSlam', knockback: 1.5 },
  silver: { name: 'Iron Slam', desc: 'Hardened body slams like metal', damage: 27, range: 130, duration: 27, color: '#C0C0C0', type: 'groundSlam', knockback: 1.6 },
  corpent: { name: 'Venom Slam', desc: 'Slams hammer spreading poison', damage: 26, range: 140, duration: 27, color: '#775533', type: 'groundSlam', knockback: 1.5 },
  magneto: { name: 'Magnetic Slam', desc: 'Slams pulling metal debris', damage: 25, range: 145, duration: 26, color: '#AAAAAA', type: 'groundSlam', knockback: 1.5 },
  willow: { name: 'Root Slam', desc: 'Vines erupt from the ground', damage: 24, range: 135, duration: 26, color: '#448833', type: 'freeze', knockback: 1.4 },
  cable: { name: 'Grid Slam', desc: 'Electric slam shocking the ground', damage: 26, range: 140, duration: 26, color: '#4488CC', type: 'groundSlam', knockback: 1.5 },
  snodvor: { name: 'Frost Slam', desc: 'Slams creating ice spikes', damage: 25, range: 140, duration: 27, color: '#AADDFF', type: 'freeze', knockback: 1.4 },
  kirsten: { name: 'Burn Slam', desc: 'Slams creating fire field', damage: 27, range: 135, duration: 26, color: '#FF4400', type: 'groundSlam', knockback: 1.5 },
  volt: { name: 'Dissonance Slam', desc: 'Sound wave shatters ground', damage: 25, range: 145, duration: 26, color: '#CCAA00', type: 'groundSlam', knockback: 1.5 },
  temple: { name: 'Dismantle Slam', desc: 'Shatters ground into fragments', damage: 26, range: 140, duration: 27, color: '#AA6633', type: 'groundSlam', knockback: 1.5 },
  nightmare: { name: 'Nightmare Slam', desc: 'Dark mist erupts on impact', damage: 25, range: 135, duration: 26, color: '#442266', type: 'groundSlam', knockback: 1.4 },
  hazel: { name: 'Thorn Slam', desc: 'Thorned vines burst from ground', damage: 24, range: 135, duration: 26, color: '#2D5A1B', type: 'freeze', knockback: 1.4 },
  whami: { name: 'Chaos Slam', desc: 'Unpredictable alchemical slam', damage: 26, range: 140, duration: 26, color: '#F5DEB3', type: 'groundSlam', knockback: 1.5 },
  controller: { name: 'Control Slam', desc: 'Slams with dominating force', damage: 28, range: 145, duration: 28, color: '#1A1A6A', type: 'groundSlam', knockback: 1.6 },
  evil: { name: 'Void Slam', desc: 'Slams with void energy', damage: 30, range: 150, duration: 28, color: '#AA00CC', type: 'voidDrop', knockback: 1.7 },
  life: { name: 'Genesis Slam', desc: 'Life energy erupts on impact', damage: 28, range: 145, duration: 27, color: '#44FF44', type: 'groundSlam', knockback: 1.6 },
  death: { name: 'Final Slam', desc: 'Death energy silences the ground', damage: 30, range: 150, duration: 28, color: '#AAAAAA', type: 'groundSlam', knockback: 1.7 },
  mercy: { name: 'Balance Slam', desc: 'Equilibrium wave on impact', damage: 27, range: 145, duration: 27, color: '#FF99DD', type: 'groundSlam', knockback: 1.6 },
};
// Generation II authored Down Heavy metadata. Collision geometry is supplied by
// gen2AttackAnims.js so the visual surface and hitbox remain synchronized.
Object.assign(DOWN_HEAVIES, {
  g2_renji: { name:'Iron Drill Plate', type:'gen2DownHeavy', range:120, damage:24, color:'#AEB7C1', duration:26 },
  g2_kaito: { name:'Burning Fistprints', type:'gen2DownHeavy', range:150, damage:23, color:'#FF5A24', duration:26 },
  g2_hana: { name:'Tilting Water Disc', type:'gen2DownHeavy', range:150, damage:22, color:'#42B8FF', duration:25 },
  g2_daigo: { name:'Falling Stone Slab', type:'gen2DownHeavy', range:150, damage:25, color:'#A88A67', duration:27 },
  g2_suzu: { name:'Landing Wind Burst', type:'gen2DownHeavy', range:135, damage:23, color:'#B8FFF2', duration:26 },
  g2_mai: { name:'Distant Shadow Hand', type:'gen2DownHeavy', range:160, damage:24, color:'#7650A8', duration:27 },
  g2_osamu: { name:'Ground Resonance', type:'gen2DownHeavy', range:150, damage:24, color:'#FFE38A', duration:27 },
  g2_yui: { name:'Stored Light Burst', type:'gen2DownHeavy', range:145, damage:22, color:'#FFF2A8', duration:26 },
  g2_ibuki: { name:'Circular Drain', type:'gen2DownHeavy', range:155, damage:24, color:'#D7E1E4', duration:27 },
  g2_nishikawa: { name:'Clapping Puppet Hands', type:'gen2DownHeavy', range:155, damage:24, color:'#D58CFF', duration:27 },
  g2_itto: { name:'Ground Shear', type:'gen2DownHeavy', range:145, damage:25, color:'#DDE5EA', duration:24 },
  g2_twinfoxes: { name:'Closing Foxfire', type:'gen2DownHeavy', range:145, damage:23, color:'#FF8A2A', duration:26 },
  g2_utsuro: { name:'Hollow Circle', type:'gen2DownHeavy', range:155, damage:25, color:'#7D4AA5', duration:27 },
});

// Generation III — authored Down Heavy metadata; exact collision is supplied by gen3AttackAnims.js.
Object.assign(DOWN_HEAVIES, {
  g3_takeshi:{name:'Sand Burial',type:'gen3DownHeavy',range:125,damage:25,color:'#D8B27A',duration:28},
  g3_aiko:{name:'Rib Cage',type:'gen3DownHeavy',range:130,damage:25,color:'#EDE2D2',duration:28},
  g3_haru:{name:'Glass Floor',type:'gen3DownHeavy',range:150,damage:24,color:'#BDEBFF',duration:27},
  g3_chiyo:{name:'Toxic Pool',type:'gen3DownHeavy',range:145,damage:25,color:'#76D63A',duration:28},
  g3_emi:{name:'Shock Response',type:'gen3DownHeavy',range:125,damage:23,color:'#D65A6A',duration:26},
  g3_nozomi:{name:'Briar Cage',type:'gen3DownHeavy',range:155,damage:25,color:'#4FAE46',duration:28},
  g3_masaru:{name:'Ash Collapse',type:'gen3DownHeavy',range:145,damage:25,color:'#9B9084',duration:28},
  g3_ryo:{name:'Vanishing Ground',type:'gen3DownHeavy',range:150,damage:24,color:'#C9D9E1',duration:27},
  g3_souta:{name:'Ash Wave',type:'gen3DownHeavy',range:150,damage:23,color:'#B9A99B',duration:27},
  g3_ogata:{name:'Overload Field',type:'gen3DownHeavy',range:145,damage:25,color:'#6CB9FF',duration:28},
  g3_kanenobu:{name:'Suppression Order',type:'gen3DownHeavy',range:145,damage:25,color:'#D8B33F',duration:28},
});
