// Down Heavy attacks — unique per character, different from their side heavy (heavyAttack)
export const DOWN_HEAVIES = {
  yellow: { name: 'Golden Stomp', desc: 'Enhanced ground stomp with golden shockwave', damage: 25, range: 130, duration: 24, color: '#FFD700', type: 'groundSlam', knockback: 1.5 },
  blue: { name: 'Ice Slam', desc: 'Slams trident down freezing the ground', damage: 22, range: 140, duration: 26, color: '#AADDFF', type: 'freeze', knockback: 1.3 },
  purple: { name: 'Shadow Crush', desc: 'Vanishes and slams down from above', damage: 26, range: 125, duration: 22, color: '#9944CC', type: 'teleSlash', knockback: 1.4 },
  orange: { name: 'Portal Drop', desc: 'Drops a boulder through a portal', damage: 24, range: 135, duration: 25, color: '#FF8800', type: 'portalStrike', knockback: 1.3 },
  green: { name: 'Mountain Stomp', desc: 'Slams hammer creating stone pillars', damage: 28, range: 145, duration: 28, color: '#44AA44', type: 'groundSlam', knockback: 1.6 },
  pink: { name: 'TK Slam', desc: 'Lifts opponent and slams them down', damage: 23, range: 130, duration: 24, color: '#FF66AA', type: 'voidDrop', knockback: 1.4 },
  grey: { name: 'Wall Drop', desc: 'Creates a wall and slams it down', damage: 25, range: 135, duration: 26, color: '#888888', type: 'groundSlam', knockback: 1.5 },
  turquoise: { name: 'Beast Stomp', desc: 'Transforms and stomps with beast force', damage: 26, range: 130, duration: 25, color: '#44CCAA', type: 'groundSlam', knockback: 1.5 },
  olive: { name: 'Titan Slam', desc: 'Grows massive and slams down', damage: 27, range: 150, duration: 28, color: '#808000', type: 'groundSlam', knockback: 1.6 },
  copper: { name: 'Time Stomp', desc: 'Freezes time on impact', damage: 24, range: 135, duration: 26, color: '#CC7744', type: 'freeze', knockback: 1.4 },
  emerald: { name: 'Phase Slam', desc: 'Phases through ground and erupts', damage: 23, range: 130, duration: 24, color: '#33CC66', type: 'riftUp', knockback: 1.3 },
  pearl: { name: 'Echo Slam', desc: 'Sound wave slams the ground', damage: 22, range: 140, duration: 25, color: '#EEEEDD', type: 'groundSlam', knockback: 1.4 },
  red: { name: 'Inferno Slam', desc: 'Slams down creating fire eruption', damage: 26, range: 135, duration: 26, color: '#FF3333', type: 'groundSlam', knockback: 1.5 },
  lavender: { name: 'Air Slam', desc: 'Solidifies air into a hammer', damage: 24, range: 130, duration: 25, color: '#BB88DD', type: 'groundSlam', knockback: 1.4 },
  amber: { name: 'Clone Slam', desc: 'Multiple clones slam simultaneously', damage: 25, range: 140, duration: 26, color: '#FFBB33', type: 'groundSlam', knockback: 1.5 },
  black: { name: 'Thunder Slam', desc: 'Lightning strikes on impact', damage: 27, range: 135, duration: 26, color: '#FFFF44', type: 'groundSlam', knockback: 1.5 },
  magenta: { name: 'Glue Slam', desc: 'Slams creating sticky trap', damage: 22, range: 130, duration: 26, color: '#FF44AA', type: 'freeze', knockback: 1.3 },
  indigo: { name: 'Gravity Slam', desc: 'Slams with intensified gravity', damage: 25, range: 140, duration: 26, color: '#4B0082', type: 'groundSlam', knockback: 1.5 },
  maroon: { name: 'Energy Slam', desc: 'Slams with concentrated energy', damage: 28, range: 135, duration: 27, color: '#800000', type: 'groundSlam', knockback: 1.6 },
  crimson: { name: 'Crimson Slam', desc: 'Construct blade slams the ground', damage: 26, range: 140, duration: 26, color: '#DC143C', type: 'groundSlam', knockback: 1.5 },
  scarlet: { name: 'Death Slam', desc: 'Necromantic energy erupts', damage: 25, range: 135, duration: 26, color: '#FF2400', type: 'groundSlam', knockback: 1.4 },
  white: { name: 'Heaven Slam', desc: 'Descends with holy force', damage: 26, range: 140, duration: 26, color: '#EEEEEE', type: 'groundSlam', knockback: 1.5 },
  silver: { name: 'Iron Slam', desc: 'Hardened body slams like metal', damage: 27, range: 130, duration: 27, color: '#C0C0C0', type: 'groundSlam', knockback: 1.6 },
  corpent: { name: 'Venom Slam', desc: 'Slams hammer spreading poison', damage: 26, range: 140, duration: 27, color: '#775533', type: 'groundSlam', knockback: 1.5 },
  magneto: { name: 'Magnetic Slam', desc: 'Slams pulling metal debris', damage: 25, range: 145, duration: 26, color: '#AAAAAA', type: 'groundSlam', knockback: 1.5 },
  willow: { name: 'Root Slam', desc: 'Vines erupt from the ground', damage: 24, range: 135, duration: 26, color: '#448833', type: 'freeze', knockback: 1.4 },
  cable: { name: 'Grid Slam', desc: 'Electric slam shocking the ground', damage: 26, range: 140, duration: 26, color: '#4488CC', type: 'groundSlam', knockback: 1.5 },
  snodvor: { name: 'Frost Slam', desc: 'Slams creating ice spikes', damage: 25, range: 140, duration: 27, color: '#AADDFF', type: 'freeze', knockback: 1.4 },
  kirsten: { name: 'Burn Slam', desc: 'Slams creating fire field', damage: 27, range: 135, duration: 26, color: '#FF4400', type: 'groundSlam', knockback: 1.5 },
  volt: { name: 'Dissonance Slam', desc: 'Sound wave shatters ground', damage: 25, range: 145, duration: 26, color: '#CCAA00', type: 'groundSlam', knockback: 1.5 },
  temple: { name: 'Dismantle Slam', desc: 'Shatters ground into fragments', damage: 26, range: 140, duration: 27, color: '#AA6633', type: 'groundSlam', knockback: 1.5 },
  nightmare: { name: 'Nightmare Slam', desc: 'Dark mist erupts on impact', damage: 25, range: 135, duration: 26, color: '#442266', type: 'groundSlam', knockback: 1.4 },
  hazel: { name: 'Thorn Slam', desc: 'Thorned vines burst from ground', damage: 24, range: 135, duration: 26, color: '#2D5A1B', type: 'freeze', knockback: 1.4 },
  whami: { name: 'Chaos Slam', desc: 'Unpredictable alchemical slam', damage: 26, range: 140, duration: 26, color: '#F5DEB3', type: 'groundSlam', knockback: 1.5 },
  controller: { name: 'Control Slam', desc: 'Slams with dominating force', damage: 28, range: 145, duration: 28, color: '#1A1A6A', type: 'groundSlam', knockback: 1.6 },
  evil: { name: 'Void Slam', desc: 'Slams with void energy', damage: 30, range: 150, duration: 28, color: '#AA00CC', type: 'voidDrop', knockback: 1.7 },
  life: { name: 'Genesis Slam', desc: 'Life energy erupts on impact', damage: 28, range: 145, duration: 27, color: '#44FF44', type: 'groundSlam', knockback: 1.6 },
  death: { name: 'Final Slam', desc: 'Death energy silences the ground', damage: 30, range: 150, duration: 28, color: '#AAAAAA', type: 'groundSlam', knockback: 1.7 },
  mercy: { name: 'Balance Slam', desc: 'Equilibrium wave on impact', damage: 27, range: 145, duration: 27, color: '#FF99DD', type: 'groundSlam', knockback: 1.6 },
};
// Generation II authored Down Heavy metadata. Collision geometry is supplied by
// gen2AttackAnims.js so the visual surface and hitbox remain synchronized.
Object.assign(DOWN_HEAVIES, {
  g2_renji: { name:'Iron Drill Plate', type:'gen2DownHeavy', range:120, damage:24, color:'#AEB7C1', duration:26 },
  g2_kaito: { name:'Burning Fistprints', type:'gen2DownHeavy', range:150, damage:23, color:'#FF5A24', duration:26 },
  g2_hana: { name:'Tilting Water Disc', type:'gen2DownHeavy', range:150, damage:22, color:'#42B8FF', duration:25 },
  g2_daigo: { name:'Falling Stone Slab', type:'gen2DownHeavy', range:150, damage:25, color:'#A88A67', duration:27 },
  g2_suzu: { name:'Landing Wind Burst', type:'gen2DownHeavy', range:135, damage:23, color:'#B8FFF2', duration:26 },
  g2_mai: { name:'Distant Shadow Hand', type:'gen2DownHeavy', range:160, damage:24, color:'#7650A8', duration:27 },
  g2_osamu: { name:'Ground Resonance', type:'gen2DownHeavy', range:150, damage:24, color:'#FFE38A', duration:27 },
  g2_yui: { name:'Stored Light Burst', type:'gen2DownHeavy', range:145, damage:22, color:'#FFF2A8', duration:26 },
  g2_ibuki: { name:'Circular Drain', type:'gen2DownHeavy', range:155, damage:24, color:'#D7E1E4', duration:27 },
  g2_nishikawa: { name:'Clapping Puppet Hands', type:'gen2DownHeavy', range:155, damage:24, color:'#D58CFF', duration:27 },
  g2_itto: { name:'Ground Shear', type:'gen2DownHeavy', range:145, damage:25, color:'#DDE5EA', duration:24 },
  g2_twinfoxes: { name:'Closing Foxfire', type:'gen2DownHeavy', range:145, damage:23, color:'#FF8A2A', duration:26 },
  g2_utsuro: { name:'Hollow Circle', type:'gen2DownHeavy', range:155, damage:25, color:'#7D4AA5', duration:27 },
});

// Generation IV — authored Down Heavy metadata. Animation/hitbox geometry is
// supplied by gen4AttackAnims.js.
Object.assign(DOWN_HEAVIES, {
  g4_cobalt: { name:'Falling Wall', type:'gen4DownHeavy', range:180, damage:25, color:'#3366FF', duration:26 },
  g4_cyan: { name:'Air Hammer', type:'gen4DownHeavy', range:145, damage:24, color:'#66DDFF', duration:26 },
  g4_onyx: { name:'Black Floor', type:'gen4DownHeavy', range:155, damage:25, color:'#5C3C88', duration:27 },
  g4_gold: { name:'Restoration Ring', type:'gen4DownHeavy', range:150, damage:23, color:'#FFD83D', duration:27 },
  g4_vermilion: { name:'Firefall', type:'gen4DownHeavy', range:150, damage:26, color:'#E34234', duration:26 },
  g4_umber: { name:'Fault Strike', type:'gen4DownHeavy', range:155, damage:25, color:'#9A5B32', duration:25 },
  g4_graphite: { name:'Structural Failure', type:'gen4DownHeavy', range:155, damage:24, color:'#8899AA', duration:27 },
  g4_daichi: { name:'Disruption Array', type:'gen4DownHeavy', range:150, damage:24, color:'#FFB02E', duration:27 },
  g4_renko: { name:'Extraction Well', type:'gen4DownHeavy', range:160, damage:26, color:'#A90024', duration:28 },
});

// Generation I authored Down Heavy metadata. These are separate from the
// universal ground-pound so grounded Down + Heavy selects the character move.
Object.assign(DOWN_HEAVIES, {
  g1_thunder: { name:'Orbiting Lightning Ball', type:'gen1DownHeavy', range:100, damage:22, color:'#FFFF44', duration:24 },
  g1_fire: { name:'Burning Cracks', type:'gen1DownHeavy', range:145, damage:22, color:'#FF6600', duration:18 },
  g1_water: { name:'Bouncing Water Sphere', type:'gen1DownHeavy', range:96, damage:21, color:'#3399CC', duration:24 },
  g1_grass: { name:'Vine Collapse', type:'gen1DownHeavy', range:120, damage:21, color:'#44AA44', duration:26 },
  g1_ice: { name:'Sliding Ice Block', type:'gen1DownHeavy', range:128, damage:22, color:'#AAEEFF', duration:24 },
});

// Generation V — authored Down Heavy metadata. Geometry is supplied by gen5AttackAnims.js.
Object.assign(DOWN_HEAVIES, {
  yellow:{name:'Ground Breaker',type:'gen5DownHeavy',range:125,damage:25,color:'#FFD700',duration:26},
  blue:{name:'Tidal Crush',type:'gen5DownHeavy',range:150,damage:24,color:'#4488FF',duration:27},
  purple:{name:'Smoke Drop',type:'gen5DownHeavy',range:135,damage:26,color:'#9944CC',duration:24},
  orange:{name:'Portal Trap',type:'gen5DownHeavy',range:155,damage:24,color:'#FF8800',duration:27},
  green:{name:'Fault Line',type:'gen5DownHeavy',range:160,damage:26,color:'#44AA44',duration:28},
  pink:{name:'Slam',type:'gen5DownHeavy',range:140,damage:24,color:'#FF66AA',duration:27},
  grey:{name:'Wall Cage',type:'gen5DownHeavy',range:150,damage:25,color:'#888888',duration:27},
  turquoise:{name:'Hammer Form',type:'gen5DownHeavy',range:145,damage:26,color:'#44CCAA',duration:26},
  olive:{name:'Growing Hammer',type:'gen5DownHeavy',range:155,damage:27,color:'#808000',duration:28},
  copper:{name:'Time Anchor',type:'gen5DownHeavy',range:145,damage:25,color:'#CC7744',duration:27},
  emerald:{name:'Solid Point',type:'gen5DownHeavy',range:140,damage:24,color:'#33CC66',duration:26},
  pearl:{name:'Resonant Ground',type:'gen5DownHeavy',range:150,damage:24,color:'#EEEEDD',duration:27},
  red:{name:'Flame Burst',type:'gen5DownHeavy',range:145,damage:26,color:'#FF3333',duration:27},
  lavender:{name:'Air Cage',type:'gen5DownHeavy',range:150,damage:24,color:'#BB88DD',duration:27},
  amber:{name:'Clone Collapse',type:'gen5DownHeavy',range:150,damage:25,color:'#FFBB33',duration:27},
});

// Generation V — Characters 16-39. Geometry is supplied by gen5RestAttackAnims.js.
Object.assign(DOWN_HEAVIES, {
  black:{name:'Orbiting Lightning',type:'gen5RestDownHeavy',range:150,damage:27,color:'#FFFF44',duration:27},
  magenta:{name:'Adhesive Trap',type:'gen5RestDownHeavy',range:145,damage:23,color:'#FF44AA',duration:28},
  indigo:{name:'Gravity Well',type:'gen5RestDownHeavy',range:145,damage:27,color:'#4B0082',duration:28},
  maroon:{name:'Power Dump',type:'gen5RestDownHeavy',range:155,damage:27,color:'#800000',duration:27},
  crimson:{name:'Element Armor',type:'gen5RestDownHeavy',range:145,damage:28,color:'#DC143C',duration:28},
  scarlet:{name:'Spirit Circle',type:'gen5RestDownHeavy',range:150,damage:27,color:'#FF2400',duration:28},
  white:{name:'Meteor Dive',type:'gen5RestDownHeavy',range:150,damage:26,color:'#EEEEEE',duration:26},
  silver:{name:'Meteor Body',type:'gen5RestDownHeavy',range:155,damage:28,color:'#C0C0C0',duration:29},
  corpent:{name:'Construction Drop',type:'gen5RestDownHeavy',range:155,damage:29,color:'#8B5A2B',duration:29},
  magneto:{name:'Magnetic Pile',type:'gen5RestDownHeavy',range:155,damage:28,color:'#777777',duration:29},
  willow:{name:'Root Cage',type:'gen5RestDownHeavy',range:150,damage:27,color:'#398A3F',duration:29},
  cable:{name:'Electric Snare',type:'gen5RestDownHeavy',range:150,damage:27,color:'#66CCFF',duration:28},
  snodvor:{name:'Icefall',type:'gen5RestDownHeavy',range:155,damage:28,color:'#A9E7FF',duration:28},
  kirsten:{name:'Delayed Burn',type:'gen5RestDownHeavy',range:145,damage:27,color:'#FF6A24',duration:29},
  volt:{name:'Resonance Slam',type:'gen5RestDownHeavy',range:155,damage:28,color:'#4A62B8',duration:28},
  temple:{name:'Split Ground',type:'gen5RestDownHeavy',range:165,damage:28,color:'#7A4B32',duration:29},
  nightmare:{name:'Dream Pit',type:'gen5RestDownHeavy',range:150,damage:27,color:'#A66CFF',duration:29},
  hazel:{name:'Poison Garden',type:'gen5RestDownHeavy',range:150,damage:27,color:'#355C35',duration:29},
  whami:{name:'Poison Mix',type:'gen5RestDownHeavy',range:150,damage:27,color:'#C28A32',duration:29},
  controller:{name:'Compression',type:'gen5RestDownHeavy',range:150,damage:28,color:'#6A4FB3',duration:28},
  evil:{name:'Erased Ground',type:'gen5RestDownHeavy',range:145,damage:29,color:'#111111',duration:28},
  life:{name:'Rebirth Pulse',type:'gen5RestDownHeavy',range:155,damage:27,color:'#67D88A',duration:29},
  death:{name:'End Point',type:'gen5RestDownHeavy',range:150,damage:28,color:'#282044',duration:29},
  mercy:{name:'Compassion Field',type:'gen5RestDownHeavy',range:150,damage:24,color:'#F2E8FF',duration:28},
});
