// Guardians — primordial cosmic entities. Not heroes, not villains — their own category.
// Life, Death, and Mercy are the fragmented remnants of the original cosmic forces.

export const GUARDIANS = [
  {
    id: 'life', name: 'Life', title: 'The First Light', color: '#44FF44', secondaryColor: '#88FF88',
    weapon: 'Spirit Orbs', power: 'Second Chance', isGuardian: true, isSpirit: true,
    stats: { power: 4, speed: 8, defense: 8, utility: 10, control: 5 },
    lore: 'The primordial force of Expansion, Growth, and Possibility. One of the original Four. Fragmented into Element 6 alongside Mercy, Death, and Evil.',
    heavyAttack: { name: "Expansion Wave", desc: "Life sends a concentrated wave forward that continuously expands as it travels, becoming wider but weaker toward its edge.", damage: 20, range: 88, duration: 13, color: "#44FF44", type: "moving", knockback: 1.1, hitboxProfile: "moving", knockbackProfile: "forward" },
    signatures: { side: { name: "Possibility", desc: "Life creates two small energy paths in front of himself. One becomes real at the last moment, producing a short strike from an unexpected angle.", damage: 11, range: 138, duration: 10, color: "#44FF44", type: "forward", knockback: 0.8, hitboxProfile: "forward", knockbackProfile: "forward" }, up: { name: "New Beginning", desc: "Life creates a small glowing point beneath himself that rapidly expands into a platform, launching him upward.", damage: 11, range: 126, duration: 10, color: "#44FF44", type: "ground", knockback: 0.8, hitboxProfile: "ground", knockbackProfile: "up" }, down: { name: "Renew", desc: "Life restores a small broken-looking energy shape beneath himself, causing it to reform and burst outward.", damage: 11, range: 126, duration: 10, color: "#44FF44", type: "ground", knockback: 0.8, hitboxProfile: "ground", knockbackProfile: "radial" } },
    superMove: { name: "Second Chance", desc: "Life creates a small sphere around himself representing a possibility that has not yet been realized. The sphere rapidly expands, contracts, and reforms several times. Life then forces all of those possible states into one moment, producing one enormous concentrated burst centered around himself.", damage: 32, range: 118, duration: 26, color: "#44FF44", type: "radial", knockback: 1.4, hitboxProfile: "radial", knockbackProfile: "radial" },
  },
  {
    id: 'death', name: 'Death', title: 'The Final Silence', color: '#AAAAAA', secondaryColor: '#CCCCCC', whiteEyes: true,
    weapon: 'Spirit Orbs', power: 'Gambit', isGuardian: true, isSpirit: true,
    stats: { power: 9, speed: 5, defense: 7, utility: 6, control: 8 },
    lore: 'The primordial force of Closure, Endings, and Necessary Silence. One of the original Four. Not evil — simply the natural conclusion to all things.',
    heavyAttack: { name: "Closure", desc: "Death extends one hand and creates a large horizontal closing line. The line begins wide, narrows rapidly, and disappears at its center.", damage: 30, range: 138, duration: 13, color: "#AAAAAA", type: "forward", knockback: 1.1, hitboxProfile: "forward", knockbackProfile: "forward" },
    signatures: { side: { name: "Final Step", desc: "Death takes one deliberate step forward and creates a thin closing line in front of himself. The line disappears immediately after contact.", damage: 16.5, range: 138, duration: 10, color: "#AAAAAA", type: "forward", knockback: 0.8, hitboxProfile: "forward", knockbackProfile: "forward" }, up: { name: "Final Rise", desc: "Death creates a narrow dark mark above himself and closes it shut, producing a compact upward force.", damage: 16.5, range: 150, duration: 10, color: "#AAAAAA", type: "vertical", knockback: 0.8, hitboxProfile: "vertical", knockbackProfile: "up" }, down: { name: "Closing Point", desc: "Death places a small dark point beneath himself. The point contracts inward and releases a downward impact.", damage: 16.5, range: 126, duration: 10, color: "#AAAAAA", type: "ground", knockback: 0.8, hitboxProfile: "ground", knockbackProfile: "down" } },
    superMove: { name: "The End", desc: "Death creates a small, silent sphere around himself. Sound and visual motion inside the sphere briefly become muted. The sphere contracts completely toward Death, then suddenly releases everything it contained outward in one enormous concentrated impact.", damage: 48, range: 118, duration: 26, color: "#AAAAAA", type: "radial", knockback: 1.4, hitboxProfile: "radial", knockbackProfile: "radial" },
  },
  {
    id: 'mercy', name: 'Mercy', title: 'The Gentle Balance', color: '#FF99DD', secondaryColor: '#FFBBEE',
    weapon: 'Spirit Orbs', power: 'Healing', isGuardian: true, isSpirit: true,
    stats: { power: 3, speed: 7, defense: 9, utility: 10, control: 6 },
    lore: 'The primordial force of Restraint, Compassion, and Forgiveness. One of the original Four. Maintains equilibrium between all forces.',
    heavyAttack: { name: "Equilibrium", desc: "Mercy creates two opposing energy waves in front of herself. One pulls inward while the other pushes outward, meeting at a single point and producing a concentrated impact.", damage: 18, range: 155, duration: 13, color: "#FF99DD", type: "line", knockback: 1.1, hitboxProfile: "line", knockbackProfile: "radial" },
    signatures: { side: { name: "Forgiving Palm", desc: "Mercy extends one hand and releases a compact pulse that interrupts an opponent's momentum and sends them away.", damage: 9.9, range: 118, duration: 10, color: "#FF99DD", type: "radial", knockback: 0.8, hitboxProfile: "radial", knockbackProfile: "forward" }, up: { name: "Gentle Lift", desc: "Mercy creates a small restorative field beneath herself that gently lifts her upward while pushing nearby opponents away.", damage: 9.9, range: 118, duration: 10, color: "#FF99DD", type: "radial", knockback: 0.8, hitboxProfile: "radial", knockbackProfile: "up" }, down: { name: "Restraint", desc: "A small healing-energy ring appears beneath Mercy and expands just enough to slow and push nearby opponents outward.", damage: 9.9, range: 118, duration: 10, color: "#FF99DD", type: "radial", knockback: 0.8, hitboxProfile: "radial", knockbackProfile: "radial" } },
    superMove: { name: "Mercy's Balance", desc: "Mercy creates a large but tightly contained sphere around herself. Inside the sphere, opposing forces are brought toward equilibrium. Movement, momentum, and energy are briefly drawn toward the center. Mercy then releases the accumulated imbalance outward in one enormous controlled pulse, launching everyone around her away while leaving the center completely calm. AND JUST FOR YOUR INFORMATION ALL THESE ATTACKS/SUPERS SHOULD HAPPEN VERY QUICKLY EVEN IF THE DESCRIPTUON MAKES YOU THINK SLOWLY. ALSO ALL THE ATTACKS SHOULD BE CHANGED IN THE HERO CODEX AND MEET THE CAHRACTERS ALSO.", damage: 28.8, range: 118, duration: 26, color: "#FF99DD", type: "radial", knockback: 1.4, hitboxProfile: "radial", knockbackProfile: "radial" },
  },
];

export const getGuardianById = (id) => GUARDIANS.find(g => g.id === id);