// Hero data — each hero has: weapon, power, heavyAttack (unique), signatures (side/up/down), superMove
// Heavy attacks are unique per-hero special strikes usable regularly in combat.

export const HEROES = [
  {
    id: 'yellow', name: 'Yellow', title: 'The Awakened One', color: '#FFD700', secondaryColor: '#FFA500',
    weapon: 'Gauntlets', power: 'Enhance', unlockOrder: 0,
    stats: { power: 7, speed: 10, defense: 5, utility: 6, control: 7 },
    lore: 'Fastest hero alive. Can enhance every aspect of his body — strength, speed, durability, reflexes. The longer he focuses, the stronger he becomes.',
    heavyAttack: { name: 'Blitz Punch', desc: 'Channels Enhance through his body, glowing gold before launching forward with a shockwave-launching punch', damage: 22, range: 170, duration: 22, color: '#FFD700', type: 'dash', knockback: 1.3 },
    signatures: {
      side: { name: 'Speed Dash', desc: 'Dashes forward with a golden trail, hitting everything in path', duration: 20, damage: 18, range: 200, color: '#FFD700', type: 'dash' },
      up: { name: 'Boost Launch', desc: 'Enhances legs and launches upward with golden shockwave', duration: 18, damage: 15, range: 120, color: '#FFA500', type: 'launch' },
      down: { name: 'Ground Slam', desc: 'Speed-enhanced stomp that sends golden cracks through the ground', duration: 22, damage: 20, range: 150, color: '#FFD700', type: 'groundSlam' },
    },
    superMove: { name: 'Limit Break', desc: 'Removes his body\'s normal limits — golden afterimages, shockwave punches, unmatched speed and strength', duration: 60, damage: 45, color: '#FFD700' },
  },
  {
    id: 'blue', name: 'Blue', title: 'The Tidecaller', color: '#4488FF', secondaryColor: '#66CCFF',
    weapon: 'Trident', power: 'H2O', unlockOrder: 1,
    stats: { power: 6, speed: 5, defense: 8, utility: 10, control: 6 },
    lore: 'Controls water in every form — summoning, pressurized blasts, ice, moisture manipulation. Versatile battlefield stabilizer.',
    heavyAttack: { name: 'Water Wheel', desc: 'Spins his trident creating a giant spinning wheel of water that rolls across the battlefield before shattering into ice fragments', damage: 20, range: 190, duration: 26, color: '#4488FF', type: 'wave', knockback: 1.2 },
    signatures: {
      side: { name: 'Tidal Wave', desc: 'Summons a crashing wave that pushes enemies sideways', duration: 25, damage: 16, range: 180, color: '#4488FF', type: 'wave' },
      up: { name: 'Geyser Burst', desc: 'Erupts a water geyser upward from beneath', duration: 20, damage: 17, range: 130, color: '#66CCFF', type: 'geyser' },
      down: { name: 'Ice Floor', desc: 'Freezes the ground in a radius, trapping enemies', duration: 30, damage: 12, range: 160, color: '#AADDFF', type: 'freeze' },
    },
    superMove: { name: 'Leviathan\'s Wrath', desc: 'Summons a massive tidal wave that sweeps the stage, then instantly freezes into enormous ice spikes', duration: 55, damage: 40, color: '#4488FF' },
  },
  {
    id: 'purple', name: 'Purple', title: 'The Silent Blade', color: '#9944CC', secondaryColor: '#CC66FF',
    weapon: 'Katana', power: 'Ninja', unlockOrder: 2,
    stats: { power: 8, speed: 9, defense: 4, utility: 5, control: 9 },
    lore: 'Elite assassin with incredible agility, stealth, and shadow movement. Strikes with precision before enemies realize he\'s there.',
    heavyAttack: { name: 'Shadow Dash', desc: 'Disappears in a cloud of smoke before instantly appearing behind his opponent with a devastating katana slash', damage: 24, range: 180, duration: 20, color: '#9944CC', type: 'teleSlash', knockback: 1.4 },
    signatures: {
      side: { name: 'Shadow Slash', desc: 'Teleports behind enemy and slashes with shadow blade', duration: 18, damage: 20, range: 170, color: '#9944CC', type: 'teleSlash' },
      up: { name: 'Rising Shadow', desc: 'Becomes a shadow spiral rising upward, slicing anything near', duration: 16, damage: 18, range: 110, color: '#CC66FF', type: 'spiralRise' },
      down: { name: 'Shadow Pin', desc: 'Pins enemy shadow to the ground, immobilizing them', duration: 28, damage: 10, range: 140, color: '#6622AA', type: 'pin' },
    },
    superMove: { name: 'Thousand Shadows', desc: 'Vanishes completely as dozens of shadow clones surround the battlefield, each attacking before one final massive finishing slash', duration: 50, damage: 48, color: '#9944CC' },
  },
  {
    id: 'orange', name: 'Orange', title: 'The Gatekeeper', color: '#FF8800', secondaryColor: '#FFAA44',
    weapon: 'Portal Rings', power: 'Portalmaking', unlockOrder: 3,
    stats: { power: 5, speed: 8, defense: 4, utility: 10, control: 8 },
    lore: 'Creates portals that instantly transport himself, weapons, objects, attacks, or even other people. Incredibly unpredictable.',
    heavyAttack: { name: 'Portal Crash', desc: 'Opens two portals, dropping a massive boulder through one so it falls directly onto his opponent from the other', damage: 23, range: 200, duration: 24, color: '#FF8800', type: 'portalStrike', knockback: 1.3 },
    signatures: {
      side: { name: 'Portal Punch', desc: 'Opens a portal and fist emerges behind enemy', duration: 22, damage: 16, range: 200, color: '#FF8800', type: 'portalStrike' },
      up: { name: 'Rift Ascend', desc: 'Opens portal beneath feet, launches up from above', duration: 20, damage: 14, range: 150, color: '#FFAA44', type: 'riftUp' },
      down: { name: 'Void Drop', desc: 'Opens portal beneath enemy, they fall and get hit from below', duration: 26, damage: 18, range: 160, color: '#CC6600', type: 'voidDrop' },
    },
    superMove: { name: 'Dimensional Collapse', desc: 'Fills the battlefield with dozens of portals — weapons, rocks, explosions rain from every direction before every portal collapses into one gigantic explosion', duration: 55, damage: 42, color: '#FF8800' },
  },
  {
    id: 'green', name: 'Green', title: 'The Mountain', color: '#44AA44', secondaryColor: '#66CC66',
    weapon: 'War Hammer', power: 'Earthbending', unlockOrder: 4,
    stats: { power: 8, speed: 4, defense: 10, utility: 8, control: 5 },
    lore: 'Controls stone, dirt, rock, sand, and terrain. Reshapes battlefields, creates walls, summons pillars, raises entire sections of land.',
    heavyAttack: { name: 'Earth Breaker', desc: 'Slams his hammer into the ground, causing enormous stone pillars to erupt beneath nearby opponents', damage: 25, range: 160, duration: 26, color: '#44AA44', type: 'groundSlam', knockback: 1.5 },
    signatures: {
      side: { name: 'Boulder Charge', desc: 'Encases arm in stone and charges forward', duration: 24, damage: 19, range: 160, color: '#44AA44', type: 'boulderCharge' },
      up: { name: 'Stone Pillar', desc: 'Raises a stone pillar from the ground that launches enemies', duration: 22, damage: 16, range: 120, color: '#66CC66', type: 'pillar' },
      down: { name: 'Earthquake', desc: 'Slams ground creating seismic ripples', duration: 28, damage: 22, range: 180, color: '#886633', type: 'quake' },
    },
    superMove: { name: 'Continental Shift', desc: 'Reshapes the battlefield itself — massive cliffs rise, mountains erupt from below, gigantic stone spikes burst across the stage', duration: 60, damage: 44, color: '#44AA44' },
  },
  {
    id: 'pink', name: 'Pink', title: 'The Mind Queen', color: '#FF66AA', secondaryColor: '#FF99CC',
    weapon: 'Boomerang Shield', power: 'Mind Control', unlockOrder: 5,
    stats: { power: 9, speed: 8, defense: 4, utility: 6, control: 8 },
    lore: 'Can move nearly anything with her mind — lift enemies, redirect attacks, stop projectiles, manipulate weapons, crush objects without touching them.',
    heavyAttack: { name: 'Psychic Crush', desc: 'Traps an opponent in midair with telekinesis before launching her shield around them several times and slamming it into them with incredible force', damage: 24, range: 150, duration: 28, color: '#FF66AA', type: 'freeze', knockback: 1.4 },
    signatures: {
      side: { name: 'TK Push', desc: 'Massive telekinetic wave shoves enemies sideways', duration: 20, damage: 20, range: 190, color: '#FF66AA', type: 'tkPush' },
      up: { name: 'Levitate Crush', desc: 'Lifts enemy upward then slams them back down', duration: 24, damage: 22, range: 130, color: '#FF99CC', type: 'levCrush' },
      down: { name: 'Mind Press', desc: 'Pushes enemy into the ground with mental force', duration: 26, damage: 24, range: 140, color: '#CC4488', type: 'mindPress' },
    },
    superMove: { name: 'Telekinetic Storm', desc: 'Unleashes the full power of her mind — everything nearby floats before she hurls rocks, weapons, debris, and pieces of the stage at opponents all at once', duration: 55, damage: 50, color: '#FF66AA' },
  },
  {
    id: 'grey', name: 'Grey', title: 'The Fortress', color: '#888888', secondaryColor: '#AAAAAA',
    weapon: 'Tower Shield', power: 'Walls', unlockOrder: 6,
    stats: { power: 4, speed: 3, defense: 10, utility: 9, control: 9 },
    lore: 'Instantly creates incredibly durable walls and barriers. Blocks attacks, traps enemies, reinforces allies, reshapes the battlefield defensively.',
    heavyAttack: { name: 'Fortress Slam', desc: 'Creates two enormous walls on opposite sides of his opponent — they slam together like giant stone doors before exploding outward', damage: 23, range: 150, duration: 28, color: '#888888', type: 'cage', knockback: 1.4 },
    signatures: {
      side: { name: 'Wall Ram', desc: 'Creates a wall and shoves it forward into enemy', duration: 26, damage: 17, range: 170, color: '#888888', type: 'wallRam' },
      up: { name: 'Rising Barrier', desc: 'Raises a wall beneath that lifts enemies skyward', duration: 22, damage: 14, range: 110, color: '#AAAAAA', type: 'barrierUp' },
      down: { name: 'Cage Trap', desc: 'Walls form a cage around the enemy, trapping and crushing', duration: 30, damage: 20, range: 150, color: '#666666', type: 'cage' },
    },
    superMove: { name: 'Citadel', desc: 'Rapidly constructs an entire fortress around himself — massive walls, towers, barricades rise from the ground before collapsing outward onto enemies', duration: 60, damage: 38, color: '#888888' },
  },
  {
    id: 'turquoise', name: 'Turquoise', title: 'The Mimic', color: '#44CCAA', secondaryColor: '#66EECC',
    weapon: 'Spear', power: 'Shapeshift', unlockOrder: 7,
    stats: { power: 6, speed: 8, defense: 6, utility: 8, control: 7 },
    lore: 'Can transform his body into different creatures, alter his appearance, stretch limbs, and adapt body parts into different forms.',
    heavyAttack: { name: 'Predator Strike', desc: 'Transforms his arm into a giant beast claw while extending his spear, lunging forward with a brutal sweeping attack', damage: 22, range: 180, duration: 22, color: '#44CCAA', type: 'beastLunge', knockback: 1.3 },
    signatures: {
      side: { name: 'Beast Lunge', desc: 'Shifts into a beast form and lunges forward with claws', duration: 20, damage: 19, range: 170, color: '#44CCAA', type: 'beastLunge' },
      up: { name: 'Wing Rise', desc: 'Shifts wings and rises with a cutting updraft', duration: 18, damage: 16, range: 130, color: '#66EECC', type: 'wingRise' },
      down: { name: 'Serpent Strike', desc: 'Shifts into serpent form and strikes downward', duration: 22, damage: 21, range: 140, color: '#228866', type: 'serpent' },
    },
    superMove: { name: 'Apex Evolution', desc: 'Rapidly shifts between multiple powerful beast forms — wolf, eagle, serpent, bear, and dragon-like creature — performing a different attack with each', duration: 50, damage: 44, color: '#44CCAA' },
  },
  {
    id: 'olive', name: 'Olive', title: 'The Titan', color: '#808000', secondaryColor: '#AAAA44',
    weapon: 'Staff', power: 'Growth', unlockOrder: 8,
    stats: { power: 5, speed: 6, defense: 7, utility: 10, control: 7 },
    lore: 'Can increase or decrease the size of himself, his weapon, enemies, and nearby objects. Controls space and overwhelms opponents.',
    heavyAttack: { name: 'Titan Swing', desc: 'Enlarges his staff several times its normal size before sweeping it across the battlefield', damage: 23, range: 200, duration: 24, color: '#808000', type: 'crimsonBlade', knockback: 1.5 },
    signatures: {
      side: { name: 'Giant Fist', desc: 'Grows fist to massive size and punches', duration: 24, damage: 22, range: 180, color: '#808000', type: 'giantFist' },
      up: { name: 'Shrink Escape', desc: 'Shrinks tiny then expands upward rapidly', duration: 18, damage: 15, range: 120, color: '#AAAA44', type: 'shrinkExpand' },
      down: { name: 'Micro Barrage', desc: 'Shrinks to micro size and rapid-attacks from below', duration: 26, damage: 18, range: 130, color: '#606000', type: 'microBarrage' },
    },
    superMove: { name: 'Colossal Growth', desc: 'Grows into a gigantic titan towering over the battlefield — attacks gain massive range and devastating knockback before returning to normal', duration: 55, damage: 42, color: '#808000' },
  },
  {
    id: 'copper', name: 'Copper', title: 'The Timekeeper', color: '#CC7744', secondaryColor: '#DD9966',
    weapon: 'Pocket Watch Blade', power: 'Time', unlockOrder: 9,
    stats: { power: 6, speed: 7, defense: 5, utility: 8, control: 9 },
    lore: 'Can briefly freeze time, slow moments down, and precisely manipulate tiny segments of time. Requires perfect timing and concentration.',
    heavyAttack: { name: 'Frozen Moment', desc: 'Freezes his opponent in time for a brief instant, calmly walks behind them, and delivers a powerful slash the moment time resumes', damage: 24, range: 180, duration: 24, color: '#CC7744', type: 'teleSlash', knockback: 1.4 },
    signatures: {
      side: { name: 'Chrono Strike', desc: 'Freezes time locally and strikes during the pause', duration: 22, damage: 20, range: 160, color: '#CC7744', type: 'chronoStrike' },
      up: { name: 'Time Lift', desc: 'Freezes enemy in time mid-air, then uppercuts', duration: 20, damage: 18, range: 120, color: '#DD9966', type: 'timeLift' },
      down: { name: 'Temporal Cage', desc: 'Creates a time-frozen zone that traps enemy', duration: 28, damage: 16, range: 150, color: '#AA5522', type: 'temporalCage' },
    },
    superMove: { name: 'Time Fracture', desc: 'Shatters the flow of time across the battlefield — everything freezes while he moves freely, delivering multiple attacks before time resumes and every hit lands simultaneously', duration: 60, damage: 46, color: '#CC7744' },
  },
  {
    id: 'emerald', name: 'Emerald', title: 'The Phantom', color: '#33CC66', secondaryColor: '#55EE88',
    weapon: 'Dual Daggers', power: 'Phase', unlockOrder: 10,
    stats: { power: 5, speed: 9, defense: 3, utility: 8, control: 10 },
    lore: 'Can become completely intangible, passing through walls, attacks, and even enemies. Can choose which parts of his body phase.',
    heavyAttack: { name: 'Phantom Strike', desc: 'Phases into the ground, disappears beneath his opponent, then emerges behind them with a rapid cross-slash from both daggers', damage: 21, range: 180, duration: 22, color: '#33CC66', type: 'phaseStrike', knockback: 1.3 },
    signatures: {
      side: { name: 'Phase Strike', desc: 'Phases through enemy and strikes from behind', duration: 18, damage: 17, range: 180, color: '#33CC66', type: 'phaseStrike' },
      up: { name: 'Intangible Rise', desc: 'Phases upward through platforms, striking from below', duration: 16, damage: 15, range: 120, color: '#55EE88', type: 'intangibleRise' },
      down: { name: 'Ghost Grab', desc: 'Phases hand into ground to grab enemy from below', duration: 24, damage: 19, range: 140, color: '#228844', type: 'ghostGrab' },
    },
    superMove: { name: 'Ghost Realm', desc: 'Completely phases out of reality — becomes untouchable for several seconds, rapidly phasing through enemies while striking from impossible angles before finishing with one massive dual-dagger slash', duration: 50, damage: 40, color: '#33CC66' },
  },
  {
    id: 'pearl', name: 'Pearl', title: 'The Seeker', color: '#EEEEDD', secondaryColor: '#FFFFFF',
    weapon: 'Sound Bow', power: 'Echo Location', unlockOrder: 11,
    stats: { power: 4, speed: 6, defense: 6, utility: 9, control: 10 },
    lore: 'Sees the world through sound. Every movement, vibration, and heartbeat creates an image in her mind — detects invisible enemies, predicts movement.',
    heavyAttack: { name: 'Resonance Pulse', desc: 'Fires a vibrating sound arrow that explodes into a powerful sonic shockwave, knocking enemies away', damage: 20, range: 200, duration: 24, color: '#EEEEDD', type: 'sonicPulse', knockback: 1.4 },
    signatures: {
      side: { name: 'Sonic Pulse', desc: 'Sends a concentrated sound wave that stuns and damages', duration: 22, damage: 14, range: 190, color: '#EEEEDD', type: 'sonicPulse' },
      up: { name: 'Echo Lift', desc: 'Sound waves bounce upward carrying the enemy', duration: 20, damage: 13, range: 130, color: '#FFFFFF', type: 'echoLift' },
      down: { name: 'Resonance Trap', desc: 'Creates vibrating sound field on the ground', duration: 26, damage: 16, range: 150, color: '#CCCCBB', type: 'resonance' },
    },
    superMove: { name: 'Symphony of Echoes', desc: 'Releases a massive sound dome across the battlefield — every footstep and movement creates explosive sound bursts while giant resonance waves continuously sweep the arena', duration: 55, damage: 38, color: '#EEEEDD' },
  },
  {
    id: 'red', name: 'Red', title: 'The Inferno', color: '#FF3333', secondaryColor: '#FF6644',
    weapon: 'Fire Sword', power: 'Fire', unlockOrder: 12,
    stats: { power: 10, speed: 7, defense: 5, utility: 4, control: 9 },
    lore: 'Creates and controls fire — ignites weapons, launches fireballs, creates walls of flame, manipulates heat. Flames grow stronger with emotion.',
    heavyAttack: { name: 'Inferno Slash', desc: 'Ignites his sword before unleashing a massive flaming crescent that burns everything in front of him', damage: 24, range: 200, duration: 22, color: '#FF3333', type: 'crimsonBlade', knockback: 1.4 },
    signatures: {
      side: { name: 'Flame Jet', desc: 'Shoots a concentrated jet of fire horizontally', duration: 20, damage: 21, range: 200, color: '#FF3333', type: 'flameJet' },
      up: { name: 'Fire Pillar', desc: 'Erupts a column of fire upward', duration: 18, damage: 19, range: 130, color: '#FF6644', type: 'firePillar' },
      down: { name: 'Inferno Ring', desc: 'Creates a ring of fire around self that expands', duration: 24, damage: 23, range: 170, color: '#CC2200', type: 'infernoRing' },
    },
    superMove: { name: 'Phoenix Inferno', desc: 'Surrounds himself in roaring flames before summoning a gigantic phoenix made entirely of fire — it flies across the battlefield before exploding into an enormous inferno', duration: 55, damage: 48, color: '#FF3333' },
  },
  {
    id: 'lavender', name: 'Lavender', title: 'The Sky Sculptor', color: '#BB88DD', secondaryColor: '#DDAAFF',
    weapon: 'Spear', power: 'Air Solidification', unlockOrder: 13,
    stats: { power: 6, speed: 7, defense: 7, utility: 8, control: 7 },
    lore: 'Compresses and hardens air into solid objects — platforms, barriers, weapons, cages, and spikes from seemingly empty space.',
    heavyAttack: { name: 'Air Prison', desc: 'Traps an opponent inside a solid-air cage before a giant air spike erupts through the center', damage: 22, range: 150, duration: 28, color: '#BB88DD', type: 'cage', knockback: 1.3 },
    signatures: {
      side: { name: 'Air Blade', desc: 'Solidifies air into a blade and slashes forward', duration: 20, damage: 18, range: 170, color: '#BB88DD', type: 'airBlade' },
      up: { name: 'Air Platform Launch', desc: 'Creates solid air platform that launches upward', duration: 18, damage: 15, range: 120, color: '#DDAAFF', type: 'airLaunch' },
      down: { name: 'Vacuum Crush', desc: 'Solidifies air around enemy, crushing inward', duration: 26, damage: 21, range: 140, color: '#9966BB', type: 'vacuumCrush' },
    },
    superMove: { name: 'Crystal Atmosphere', desc: 'Transforms the air around the battlefield into thousands of floating solid-air blades, platforms, and crystal-like structures that rain down onto opponents', duration: 55, damage: 43, color: '#BB88DD' },
  },
  {
    id: 'amber', name: 'Amber', title: 'The Legion', color: '#FFBB33', secondaryColor: '#FFDD66',
    weapon: 'Dual Short Swords', power: 'Clone', unlockOrder: 14,
    stats: { power: 7, speed: 8, defense: 5, utility: 7, control: 8 },
    lore: 'Creates perfect copies of herself. Each clone fights independently, allowing her to overwhelm enemies from multiple directions.',
    heavyAttack: { name: 'Triple Assault', desc: 'Creates two clones that instantly surround her opponent before all three attack simultaneously with synchronized sword strikes', damage: 23, range: 170, duration: 24, color: '#FFBB33', type: 'cloneRush', knockback: 1.4 },
    signatures: {
      side: { name: 'Clone Rush', desc: 'Creates two clones that charge alongside', duration: 22, damage: 20, range: 180, color: '#FFBB33', type: 'cloneRush' },
      up: { name: 'Clone Toss', desc: 'Clone throws the original upward as an attack', duration: 18, damage: 16, range: 130, color: '#FFDD66', type: 'cloneToss' },
      down: { name: 'Clone Pile', desc: 'Clones dogpile on top of enemy', duration: 26, damage: 22, range: 140, color: '#DD9911', type: 'clonePile' },
    },
    superMove: { name: 'Clone Army', desc: 'Creates an entire army of clones — dozens of copies rush across the battlefield, attacking from every direction before disappearing', duration: 55, damage: 44, color: '#FFBB33' },
  },
  {
    id: 'black', name: 'Black', title: 'The Storm King', color: '#333333', secondaryColor: '#FFFF44', whiteEyes: true,
    weapon: 'Lightning Axe', power: 'Thunder', unlockOrder: 15,
    stats: { power: 10, speed: 5, defense: 8, utility: 4, control: 8 },
    lore: 'Controls lightning, electricity, and thunderstorms. Charges weapons with electricity, summons lightning from the sky, moves with explosive electrical bursts.',
    heavyAttack: { name: 'Thunder Crash', desc: 'Slams his axe into the ground, calling a massive bolt of lightning directly onto the impact point', damage: 26, range: 170, duration: 24, color: '#FFFF44', type: 'groundSlam', knockback: 1.6 },
    signatures: {
      side: { name: 'Lightning Bolt', desc: 'Fires a horizontal bolt of lightning', duration: 18, damage: 24, range: 210, color: '#FFFF44', type: 'lightningBolt' },
      up: { name: 'Thunder Launch', desc: 'Lightning strikes from above, launching enemies', duration: 20, damage: 22, range: 140, color: '#FFFF44', type: 'thunderLaunch' },
      down: { name: 'Storm Ground', desc: 'Channels lightning through the ground in all directions', duration: 24, damage: 26, range: 180, color: '#CCCC00', type: 'stormGround' },
    },
    superMove: { name: 'Judgment Storm', desc: 'Dark clouds consume the battlefield as enormous lightning bolts strike randomly around the arena. Black becomes surrounded by electricity while every swing of his axe releases giant arcs of lightning', duration: 60, damage: 55, color: '#FFFF44' },
  },
  {
    id: 'magenta', name: 'Magenta', title: 'The Binder', color: '#FF44AA', secondaryColor: '#FF77CC',
    weapon: 'Glue Cannon', power: 'Glue', unlockOrder: 16,
    stats: { power: 3, speed: 5, defense: 8, utility: 10, control: 9 },
    lore: 'Creates an incredibly powerful adhesive substance. Traps enemies, glues objects together, reinforces structures, restricts movement.',
    heavyAttack: { name: 'Glue Prison', desc: 'Fires a giant glue projectile that explodes into an enormous sticky sphere, trapping anyone caught inside before blasting them away', damage: 20, range: 180, duration: 28, color: '#FF44AA', type: 'adhesiveShot', knockback: 1.3 },
    signatures: {
      side: { name: 'Adhesive Shot', desc: 'Shoots a glob of adhesive that binds and damages', duration: 24, damage: 15, range: 180, color: '#FF44AA', type: 'adhesiveShot' },
      up: { name: 'Sticky Trap', desc: 'Launches adhesive upward that pulls enemies down', duration: 22, damage: 13, range: 130, color: '#FF77CC', type: 'stickyTrap' },
      down: { name: 'Web Bind', desc: 'Creates adhesive web on ground that immobilizes', duration: 28, damage: 18, range: 160, color: '#CC2288', type: 'webBind' },
    },
    superMove: { name: 'World Adhesive', desc: 'Covers nearly the entire battlefield in glue — giant glue pillars erupt from the floor while massive adhesive waves spread across the stage, slowing and trapping opponents', duration: 55, damage: 40, color: '#FF44AA' },
  },
  {
    id: 'indigo', name: 'Indigo', title: 'The Gravity Queen', color: '#4B0082', secondaryColor: '#7744AA',
    weapon: 'Chain', power: 'Gravity', unlockOrder: 17,
    stats: { power: 8, speed: 6, defense: 7, utility: 5, control: 9 },
    lore: 'Controls both the direction and strength of gravity. Increases gravity to pin enemies, reverses gravity to make opponents float, bends movement across the battlefield.',
    heavyAttack: { name: 'Gravity Collapse', desc: 'Wraps her chain around an opponent before dramatically increasing gravity, slamming them into the ground with incredible force', damage: 25, range: 170, duration: 26, color: '#4B0082', type: 'freeze', knockback: 1.5 },
    signatures: {
      side: { name: 'Gravity Crush', desc: 'Increases gravity on enemy, slamming them sideways', duration: 22, damage: 23, range: 180, color: '#4B0082', type: 'gravCrush' },
      up: { name: 'Gravity Invert', desc: 'Inverts gravity launching enemies skyward helplessly', duration: 20, damage: 20, range: 140, color: '#7744AA', type: 'gravInvert' },
      down: { name: 'Singularity', desc: 'Creates a gravity well that pulls and crushes', duration: 28, damage: 26, range: 160, color: '#330055', type: 'singularity' },
    },
    superMove: { name: 'Singularity', desc: 'Creates a miniature black hole that pulls everything toward its center. After absorbing enough energy, it violently collapses into a devastating gravity explosion', duration: 60, damage: 52, color: '#4B0082' },
  },
  {
    id: 'maroon', name: 'Maroon', title: 'The Reactor', color: '#800000', secondaryColor: '#AA3333',
    weapon: 'Energy Orb', power: 'Energy', unlockOrder: 18,
    stats: { power: 9, speed: 6, defense: 6, utility: 6, control: 8 },
    lore: 'Absorbs, stores, redirects, and releases nearly every form of energy. The more attacks he absorbs, the stronger his own attacks become.',
    heavyAttack: { name: 'Overcharge Burst', desc: 'Channels absorbed energy into his orb before firing a concentrated energy blast that explodes on impact', damage: 24, range: 200, duration: 24, color: '#800000', type: 'energyBeam', knockback: 1.4 },
    signatures: {
      side: { name: 'Energy Beam', desc: 'Fires concentrated absorbed energy horizontally', duration: 22, damage: 22, range: 200, color: '#800000', type: 'energyBeam' },
      up: { name: 'Absorption Burst', desc: 'Absorbs then releases energy upward in a column', duration: 20, damage: 19, range: 130, color: '#AA3333', type: 'absorbBurst' },
      down: { name: 'Overload', desc: 'Releases stored energy in all directions from ground', duration: 26, damage: 24, range: 170, color: '#660000', type: 'overload' },
    },
    superMove: { name: 'Infinite Reactor', desc: 'Absorbs energy from the battlefield until his orb becomes enormous. Then unleashes a gigantic continuous energy beam capable of sweeping across the entire arena', duration: 55, damage: 50, color: '#800000' },
  },
  {
    id: 'crimson', name: 'Crimson', title: 'The Relentless', color: '#DC143C', secondaryColor: '#FF4466',
    weapon: 'Blood Blade', power: 'Element 6', unlockOrder: 19,
    stats: { power: 10, speed: 8, defense: 6, utility: 3, control: 8 },
    lore: 'Weaponizes his own Element 6 energy, forging blades, spears, shields, armor from condensed crimson energy. The longer he fights, the stronger but more unstable his constructs become.',
    heavyAttack: { name: 'Crimson Lance', desc: 'Transforms his blade into a massive spear before hurling it across the battlefield. On impact it shatters into dozens of razor-sharp crimson shards', damage: 25, range: 210, duration: 24, color: '#DC143C', type: 'energyBeam', knockback: 1.5 },
    signatures: {
      side: { name: 'Crimson Blade', desc: 'Forms a blood-red energy blade and slashes forward', duration: 20, damage: 23, range: 170, color: '#DC143C', type: 'crimsonBlade' },
      up: { name: 'Spear Launch', desc: 'Creates energy spear and launches it upward', duration: 18, damage: 20, range: 140, color: '#FF4466', type: 'spearLaunch' },
      down: { name: 'Detonation', desc: 'Compressed energy burst that implodes on ground', duration: 24, damage: 26, range: 160, color: '#AA0022', type: 'detonation' },
    },
    superMove: { name: 'Endless Arsenal', desc: 'Energy erupts around Crimson as dozens of glowing blades, spears, axes and hammers float around him. They all launch toward opponents before Crimson finishes with one enormous energy blade slash', duration: 55, damage: 52, color: '#DC143C' },
  },
  {
    id: 'scarlet', name: 'Scarlet', title: 'The Gravekeeper', color: '#FF2400', secondaryColor: '#FF5533',
    weapon: 'Scythe', power: 'Necromancy', unlockOrder: 20,
    stats: { power: 8, speed: 5, defense: 6, utility: 7, control: 9 },
    lore: 'Controls death energy and spiritual forces. Summons spectral warriors, manipulates lingering souls, creates cursed energy, channels the power of the dead.',
    heavyAttack: { name: 'Soul Reaper', desc: 'Swings her scythe, releasing a massive wave of dark spiritual energy that passes through enemies before exploding behind them', damage: 24, range: 200, duration: 24, color: '#FF2400', type: 'deathWave', knockback: 1.4 },
    signatures: {
      side: { name: 'Death Wave', desc: 'Sends a wave of death-energy that decays on contact', duration: 24, damage: 21, range: 190, color: '#FF2400', type: 'deathWave' },
      up: { name: 'Soul Pull', desc: 'Pulls death-energy upward, dragging enemies with it', duration: 20, damage: 18, range: 130, color: '#FF5533', type: 'soulPull' },
      down: { name: 'Grave Rise', desc: 'Death energy erupts from below the enemy', duration: 26, damage: 23, range: 150, color: '#CC1100', type: 'graveRise' },
    },
    superMove: { name: 'Army of the Fallen', desc: 'Summons an army of spectral warriors from the spirit world. Ghostly soldiers charge across the battlefield while giant soul hands emerge from the ground, ending with one enormous death-energy explosion', duration: 60, damage: 48, color: '#FF2400' },
  },
  {
    id: 'white', name: 'White', title: 'The Sky Guardian', color: '#EEEEEE', secondaryColor: '#FFFFFF',
    weapon: 'Light Bow', power: 'Flight', unlockOrder: 21,
    stats: { power: 5, speed: 10, defense: 4, utility: 9, control: 7 },
    lore: 'Elite aerial mobility. Crucial for rescue operations. Flies at incredible speeds and attacks from the sky.',
    heavyAttack: { name: 'Sky Dive', desc: 'Flies high into the air before diving diagonally across the stage. Anyone hit is launched while white feathers trail behind', damage: 22, range: 210, duration: 22, color: '#EEEEEE', type: 'dash', knockback: 1.4 },
    signatures: {
      side: { name: 'Wind Charge', desc: 'Flies forward at high speed leaving a white trail', duration: 18, damage: 16, range: 200, color: '#EEEEEE', type: 'windCharge' },
      up: { name: 'Aerial Spiral', desc: 'Spirals upward creating a cutting wind vortex', duration: 16, damage: 15, range: 140, color: '#FFFFFF', type: 'aerialSpiral' },
      down: { name: 'Dive Bomb', desc: 'Dives from height at incredible speed', duration: 20, damage: 20, range: 150, color: '#DDDDDD', type: 'diveBomb' },
    },
    superMove: { name: 'Heaven\'s Descent', desc: 'Rises completely off-screen as glowing wings spread behind him. A barrage of light arrows rains down before he crashes through the center of the arena in a massive aerial strike', duration: 50, damage: 42, color: '#EEEEEE' },
  },
  {
    id: 'silver', name: 'Silver', title: 'The Unbreakable', color: '#C0C0C0', secondaryColor: '#E0E0E0',
    weapon: 'Chained Mace', power: 'Hardened', unlockOrder: 22,
    stats: { power: 8, speed: 4, defense: 10, utility: 5, control: 8 },
    lore: 'Former Corps leader. The most stable fighter mentally. Can harden his entire body to living metal. Died protecting the team from Evil\'s final attack.',
    heavyAttack: { name: 'Iron Breaker', desc: 'Hardens his entire body and charges forward with his chained mace. The attack has armor during startup and knocks enemies a long distance', damage: 26, range: 180, duration: 26, color: '#C0C0C0', type: 'metalCharge', knockback: 1.6, hasArmor: true },
    signatures: {
      side: { name: 'Metal Charge', desc: 'Hardens entire body to metal and charges forward', duration: 24, damage: 24, range: 170, color: '#C0C0C0', type: 'metalCharge' },
      up: { name: 'Chrome Uppercut', desc: 'Hardens fist to chrome and delivers crushing uppercut', duration: 20, damage: 22, range: 120, color: '#E0E0E0', type: 'chromeUpper' },
      down: { name: 'Iron Stomp', desc: 'Full metal body stomps creating a metal shockwave', duration: 26, damage: 25, range: 160, color: '#999999', type: 'ironStomp' },
    },
    superMove: { name: 'Titanium Fortress', desc: 'Completely transforms into living metal. His chained mace grows larger while armor plates cover his body. Becomes nearly unstoppable for several seconds and ends with a massive ground smash', duration: 60, damage: 50, color: '#C0C0C0' },
  },
];

export const getHeroById = (id) => HEROES.find(h => h.id === id);
export const getHeroByOrder = (order) => HEROES.find(h => h.unlockOrder === order);