// Full lore of THE ELEMENT 6 | Heroes in Color — the complete narrative across all ten arcs.

export const LORE_CHAPTERS = [
  {
    title: 'Prologue — When Balance Still Breathed',
    content: `Before the universe expanded, before atoms argued with gravity, before time decided to move forward—there were Four. Not rulers. Not creators in the religious sense. Forces. They did not speak in language. They existed in principle.

Life. Expansion. Growth. Possibility.
Mercy. Restraint. Compassion. Forgiveness before consequence.
Death. Closure. Endings. Necessary silence after sound.
And then—Evil. Not cruelty. Not malice. Evil was Opposition. The pressure against existence. The idea that nothing would be simpler.

For eternity, they were in equilibrium. Life created. Death concluded. Mercy softened transitions. Evil balanced expansion by limiting it. But balance is fragile when awareness grows. And Evil began to think.

The First Argument: There is no sky yet. Only endless white abstraction. Life radiates warmth. Mercy hums like distant wind. Death stands still. Evil is a distortion in the field.

Life speaks first. "Expansion has begun." Stars ignite. Mercy glows. "It is beautiful." Death nods. "It will end, as it should." Evil watches. "They will suffer." Life answers gently. "They will live." Evil sharpens. "They will multiply." Death responds calmly. "And conclude." Evil shifts closer. "Why must anything exist at all?" Silence. Mercy moves toward him. "Because existence is not harm." Evil pulses darker. "It is noise." Life expands brighter. "It is possibility." Evil's presence grows colder. "Possibility creates contradiction." Death says nothing. Mercy asks softly: "Do you wish for stillness?" Evil's voice becomes clear. "Yes." Life steps forward. "Stillness is not balance." Evil replies: "Stillness is perfection." That is when equilibrium fractures.

The Shattering: Evil does not attack violently. He compresses. He condenses. He pulls inward. Life splinters. Mercy fractures. Death cracks like glass under pressure. Their divine structure collapses into fragments that scatter across the forming universe—into stars, into planets, into atoms, into blood. Life screams—not in sound, but in expansion. Mercy scatters in sparks. Death steadies what he can. Evil stands alone in widening silence. He whispers: "At last." But the silence does not come. Because the fragments do not die. They become something unstable, imperfect, mortal.

The Birth of Element 6: When the fragments of Life, Mercy, and Death settle into material reality, they condense into a new force. Not pure divinity. Not simple physics. A broken echo. The sixth element of existence. Element 6. It does not awaken immediately. It waits. It embeds itself in bloodlines, in probability, in moments of emotional rupture. Evil watches from beyond the veil of matter. He cannot erase what has scattered. But he can influence what rises. And when humanity grows intelligent enough—the awakenings begin.`
  },
  {
    title: 'Arc I — The Creation Arc',
    content: `It begins quietly. A child in a hospital room lifts her crib with invisible force. The nurses scream. Gravity bends sideways. The ceiling fractures. This child is Indigo.

Years later, at a lakeside pier—a teenager falls in during a storm. Instead of drowning, the water rises around him. It shapes into walls. Freezes. Shatters. This is Blue.

Across the city—a boy being cornered by bullies slams his hand into the ground. The asphalt ripples. Stone erupts upward like a defensive shield. This is Green.

In a warehouse—a frightened girl screams and crates lift, twist, and hover in midair. This is Pink.

At a high school track—a runner collapses after outrunning every competitor by an impossible margin. His muscles glow faintly gold. This is Yellow.

In a cemetery at dusk—a grieving teenager feels something stir in the air. Not ghosts. Not horror. Energy. Lingering. Listening. This is Scarlet.

On a rooftop during a thunderstorm—lightning strikes a boy and bends. Coils. Waits for instruction. This is Black.

And in an empty parking structure—a calm young man watches his hand turn to metal. Not panic. Not fear. Just reflection. This is Silver.

The First Gathering: Fear spreads faster than understanding. Clips go viral. "Gravity Kid." "Water Freak." "Metal Man." Governments whisper. Civilians panic. And Silver makes a choice. He sends encrypted messages. Coordinates. One by one, they arrive at an unfinished skyscraper. Yellow first. Blue next. Green arrives cautiously. Pink floats instead of walking. Black lands with thunder cracking faintly behind him. Maroon arrives quietly, absorbing ambient electrical interference. Lavender forms air steps. Orange portals in without warning. Purple appears from shadow. White circles above before descending. Grey constructs a temporary wall perimeter. Amber arrives with two duplicates. Pearl walks calmly, eyes closed, sensing everyone. Emerald phases through a support beam. Olive adjusts size mid-step to avoid debris. Copper freezes falling dust in midair just to test himself. Red holds unstable energy orbs in his palms. Magenta binds a loose cable so it doesn't snap. Turquoise shifts form just to see reactions. Scarlet watches the sky. Indigo arrives last. Gravity feels heavier around her.

Silver steps forward. He does not raise his voice. "We are not disasters." Silence. Black folds his arms. "We are weapons." Magenta gently responds: "Only if we choose to be." Indigo studies Silver. "And who chooses?" Silver's metal fades back to skin. "We build structure. Or someone builds it for us." Purple nods once. Orange smirks. Yellow cracks his knuckles. Blue says quietly: "I don't want to drown anyone again." Green whispers: "Me neither." That night, the Hero Corps forms. Not because they trust each other—because they understand something worse is coming. And far beyond mortal sight, Evil watches. The universe is still too loud.`
  },
  {
    title: 'Arc II — The Crimson Arc',
    content: `The Hero Corps didn't become heroes overnight. They trained. They failed. They argued. And they learned quickly that power without control is worse than no power at all. Crimson was the strongest raw attacker in the Corps. Not Black. Not Indigo. Crimson. His Element 6 manifested as pure destructive output—volatile, dense, unstable. He could detonate compressed bursts of force strong enough to crack reinforced steel. And he loved pushing it.

Training Grounds — Dusk: The training arena was carved into the side of a mountain Green had reshaped months prior. Lavender formed air platforms overhead for aerial maneuvers. Grey reinforced impact zones. Pearl stood blindfolded, listening. Amber stretched her fingers before splitting into three identical copies. Emerald leaned casually against a stone pillar, phasing half his body in and out of it. Red stood across from Crimson. "First to ring-out?" Red asked. Crimson grinned. "First to drop." Silver sighed quietly. "Control. Not dominance."

The match began. Red launched controlled Element 6 orbs—precise, tactical. Crimson responded with explosive bursts that shook the entire arena. Pearl flinched. Emerald phased through a shockwave and muttered, "He's overloading again." Black crossed his arms. "He likes the noise." Magenta stepped closer to Silver. "He's escalating." Silver's eyes flickered faintly silver. Foresight activated. Three seconds. Impact. Collapse. Medics running. He exhaled. "Crimson." Crimson ignored him.

Red fired two orbs in succession—one high, one low. Crimson detonated both midair in a single blast. The mountain cracked. Green stumbled. "Hey! That's structural!" Crimson laughed. "Relax." Then he charged a blast far denser than before. Red's expression shifted. "Crim, don't—" Too late. The explosion ripped across the arena. Grey's walls shattered. Lavender's platforms dissolved. Amber's clones were thrown backward. Pearl hit the ground hard. When the smoke cleared—Emerald stood frozen mid-phase. Half solid. Half intangible. He had miscalculated the timing. The shockwave hit while he was transitioning. He collapsed. Silence swallowed the arena. Amber's clones vanished instantly as she screamed. Pearl tore off her blindfold and ran forward. "Emerald?" Red's orbs flickered violently. Crimson stared at his own hands. "I didn't… he phases through everything." Magenta knelt beside Emerald. Her voice broke. "He's not responding." Silver stepped forward slowly. He didn't need foresight to know. Crimson whispered, "I was holding back." Black's voice was low and dangerous. "No. You weren't."

Aftermath: Emerald's funeral was quiet. Pearl spoke first. "He always said phasing wasn't invincibility. Just timing." Amber couldn't speak. Red stood beside Crimson. Crimson didn't cry. He didn't move. When everyone else left, Red stayed. "You lost control." Crimson's jaw tightened. "I was stronger." "You were reckless." Crimson snapped, "He phased late." Red stepped closer. "You detonated early." Silence. Crimson's power flickered around him. "I'm not weak." Red's voice softened. "No one said you were." Crimson looked at the grave marker. "I'm not losing again." That wasn't grief. That was escalation. Silver watched from a distance. Magenta joined him. "You saw this coming." "Yes." "Why didn't you stop it?" Silver's voice was hollow. "I tried."

Crimson stopped attending training. He trained alone. Harder. Louder. More volatile. The Corps began splitting subtly. Purple and Black sided with discipline. Red stayed in the middle. Indigo watched quietly. Yellow muttered to Maroon one evening, "He's going to blow up something worse than a mountain." Maroon absorbed a stray energy pulse drifting from Crimson's distant practice. "He already did." This tension leads directly into the tournament.`
  },
  {
    title: 'Arc III — The Red & Crimson Tournament Arc',
    content: `The tournament wasn't about entertainment. It was about control. Silver organized it deliberately. "If we cannot regulate ourselves," he said during briefing, "the world will attempt to regulate us." The brackets were drawn. This time, Crimson promised restraint. Emerald's absence hung heavy. Pearl entered in his honor. Amber entered with silent fury.

Quarterfinals: Pearl vs Olive. Olive shrank the arena beneath Pearl's feet. Pearl closed her eyes. "I can still hear you." She dodged perfectly and won cleanly. Amber vs Purple. Purple dismantled two clones immediately. Amber adapted with coordinated flanking. Purple barely edged her out. Black vs Turquoise. Turquoise shifted forms rapidly. Black ended it with a single thunder strike that shattered the arena floor. Red advanced cleanly through his bracket. Crimson advanced too. He looked controlled. Too controlled.

Semifinals: Red vs Pearl. The arena quieted. Pearl bowed. "For Emerald." Red nodded. "For him." Pearl fought blindfolded again. Red launched his orbs strategically. Pearl predicted several. But Red adjusted breathing rhythm deliberately to fake patterns. One orb detonated behind her. She fell. She smiled faintly. "You changed your tempo." Red extended a hand. "You taught me that." He advanced to the finals.

Crimson vs Amber. The arena felt heavier. Amber split into four clones immediately. Crimson waited. "Come at me together." They did. He dodged precisely at first. Controlled bursts. Minimal damage. Silver leaned forward. Magenta whispered, "He's stable." Then one clone landed a direct strike. Crimson's eyes shifted. The explosion that followed was not controlled. Amber's real body was caught in the radius. She hit the ground hard. Unmoving. The smoke cleared slowly. Crimson stood alone in the center. Amber did not stand. Medics rushed again. Red ran into the arena. "No. No no no—" Silver's face was stone. Magenta knelt again. History repeating. Amber was pronounced dead within the hour. The tournament ended. Red never got his final match. Crimson disappeared that night.

Red's Change: Weeks passed. Red trained alone. His Element 6 orbs began behaving differently. They burned hotter. Longer. Instead of contained detonations—flame. Silver approached him one evening. "You've altered your manifestation." Red didn't look up. "Orbs explode and disappear." Silver waited. Red's fists ignited fully now. "Fire stays." That was the birth of Red's fire. Not from ambition. From grief. Crimson was gone. Two funerals stood where one tournament had been meant to unite them. The Corps was fractured. And somewhere—the Controller took notice.`
  },
  {
    title: 'Arc IV — The Pink Betrayal Arc',
    content: `Emerald's grave was still fresh. Amber's memorial flowers hadn't wilted. The Hero Corps kept training—but there was a tension that hadn't existed before. They weren't invincible anymore. And Pink felt something none of them admitted out loud: they were scared.

Silver's Briefing Room: Silver stood at the center table. Metal holographic projections hovered in the air. "We tighten protocols. No solo engagements. Emotional spikes will be monitored." Pink leaned back in her chair, telekinetically spinning a pen in the air. "Monitored?" Silver didn't look at her. "Yes." Yellow shifted awkwardly. Maroon crossed his arms. Black watched silently. Pink smirked. "So what, we get a babysitter now?" Silver met her eyes. "We get discipline." Pink's smile faded. After the meeting, she left without a word. Magenta followed. "You okay?" Pink stopped mid-hallway. "Do you ever feel like we're just weapons in a glass case?" Magenta tilted her head gently. "We're protectors." Pink laughed quietly. "Yeah. Protectors with supervision." Magenta reached out—not physically, just emotionally. "You don't have to fight him." "I'm not fighting him." But she was.

The First Whisper: Later that night, Pink stood alone above the city. The air shimmered behind her. "Do they trust you?" the voice asked. She didn't turn. "I know who you are." "Good." The Controller stepped forward. His presence wasn't divine like Evil. It was calculated. "I've been watching you." "Get in line." "You hesitate less than the others." Pink's telekinesis tightened unconsciously. "They hesitate because Silver tells them to." "And you don't like that." She finally turned. "I don't like being contained." The Controller circled her slowly. "You don't need him. He predicts outcomes. You disrupt them." Silence. "You could lead." That hit. Pink masked it. "You're just trying to split us." "I'm trying to show you what you are." He stepped closer. "They fear what you can do at full strength." The Controller vanished. But the idea remained.

The Shift: During a containment mission, things escalated fast. A rogue Elementor detonated shockwaves downtown. Green stabilized buildings. Blue redirected water mains. Grey shielded civilians. Pink hovered above, scanning. Silver gave orders. "Contain left quadrant. Indigo, reduce gravity spread. Yellow—" Pink moved before he finished. She crushed the rogue Elementor's energy core instantly. Efficient. Brutal. The crowd went silent. Silver looked up at her. "That wasn't necessary." Pink's voice carried down cold. "It worked." Later, in private—Silver confronted her. "You escalated unnecessarily." Pink crossed her arms. "You're upset I didn't wait for permission." "I'm upset you're acting independently." She stepped closer. "I'm not your soldier." Silver didn't flinch. "You're part of a system." Pink's eyes glowed faintly. "Maybe I don't want to be."

The Break: The next mission changed everything. A containment scenario at a power facility. Maroon absorbed unstable output. Lavender reinforced the air structure. Yellow enhanced Grey's durability. Pink hovered above the reactor core. The Controller's voice whispered: "You can end instability permanently." Pink's breathing changed. She redirected the entire energy surge outward. Not at civilians. At infrastructure. At the containment grid. Chaos. Green shouted. "Pink, stop!" Maroon strained, absorbing backlash. Black launched upward. "What are you doing?!" Pink turned slowly. "No more half-measures." Silver activated foresight. Three seconds. He saw destruction. He saw her leaving. He saw himself failing to stop it. "Pink—" She lifted him telekinetically and slammed him into reinforced steel. Not lethal. But deliberate. "You don't get to control me." The Controller appeared behind her, visible only to her. "Now." Pink ripped open the facility ceiling and vanished into the night. The world saw it live. Hero attacks hero. Trust shattered.`
  },
  {
    title: 'Arc V — The Saving Pink Arc',
    content: `The Corps did not call her a villain. They called her lost. Silver did not rage. He recalculated. Magenta refused to give up. Black was furious. "She chose this." Indigo shook her head. "No. She was nudged." Red clenched his fists. "I'll bring her back." Silver's voice was steady. "We don't kill her." Yellow looked at him sharply. "What if she tries to kill us?" Silver met his eyes. "Then we endure."

The Confrontation: They found her at the abandoned coastal refinery. Wind howled through rusted steel. Pink hovered above the ocean. The Controller stood beside her. Visible now. Maroon whispered, "So that's him." The Controller smiled faintly. "You brought the entire team." Purple stepped forward. "Let her go." "She is free." Pink's voice echoed cold. "I don't need saving." Indigo walked ahead of everyone. "No one's trying to cage you." Pink's telekinesis lifted debris around them. "You never understood me." Indigo's voice softened. "I do." The Controller interjected, "She fears being secondary." Black launched upward in lightning fury. The Controller absorbed it effortlessly. "I am beyond you."

Battle erupted. Not chaotic. Personal. Green raised barriers to protect Yellow. Grey shielded Maroon while he absorbed redirected energy. Blue froze tidal surges Pink hurled. Lavender created air cages. Red's fire cut through telekinetic constructs. Crimson fought at his side—controlled this time. Purple and White coordinated aerial pressure. Copper froze micro-moments to reposition civilians. Pearl guided movements through sound. Scarlet suppressed death-energy surges from collateral damage. It wasn't a war. It was an intervention.

Indigo finally reached Pink mid-air. Gravity inverted around them. They floated suspended above the ocean. "You think we don't see you?" Pink's eyes flickered. "They only see risk." Indigo shook her head. "They see power. And they're scared of losing you." The Controller stepped closer. "She is better without structure." Magenta's voice cut through everything. "Pink." Pink turned. Magenta hovered below, tears visible. "You're not a weapon." Silence. "You're my friend." Pink's telekinesis wavered. The Controller snapped, "They fear you!" Magenta answered calmly: "We fear losing you." Pink screamed—not in anger, but confusion. Her power surged violently. Indigo increased gravity suddenly, grounding both of them safely. Silver stepped forward slowly. He didn't attack. He deactivated foresight. "I was wrong." Everyone looked at him. "I tried to manage you instead of trust you." Pink stared at him. "You don't control me." "No," Silver said quietly. "I don't." The Controller lashed out, attempting to pull her back into influence. Black intercepted. Maroon absorbed the surge. Red's flames burned through the projection. Together, they forced the Controller to retreat. Pink collapsed to her knees. Magenta embraced her. No applause. No cheering. Just breathing. She was back.

The Cutscene — Silver Steps Down: Night. Silver stood at the balcony of his estate. Indigo joined him. "You're not okay." He exhaled. "I saw every outcome where she left. I couldn't see the one where she stayed." Indigo looked at the city lights. "You're tired." Silver nodded. "The Corps doesn't need a predictor." He turned toward her. "They need someone they'll follow." Indigo's eyes widened slightly. "Silver—" "You lead." She hesitated. "I'm not you." "I know." He placed a hand on her shoulder. "That's why." The Hero Corps assembled. Silver removed his leadership insignia. Indigo stepped forward. Pink stood beside Magenta. Red beside Crimson. Black watching silently. Yellow looked between them and whispered to Maroon, "Well. That just happened." Maroon nodded. "Yeah. It did." Silver stepped back. Not defeated. Just… finished leading.`
  },
  {
    title: 'Arc VI — The Controller War',
    content: `Pink's rescue did not end the threat. It exposed it. The Controller stopped hiding. Cities across the world began reporting coordinated Elementor uprisings. Not random awakenings. Organized strikes. Energy facilities sabotaged. Gravity distortions in financial districts. Water systems hijacked. Power grids overloaded. Silver stood inside the strategy hall at his estate—no longer leader, but still present. Indigo stood at the head now. Maroon projected a map of global disturbances. "This isn't chaos," Maroon said quietly. "It's synchronization." Black folded his arms. "He's testing perimeter." Pink stared at the map. "He's building something." Red's fire flickered faintly. "No. He's baiting us." And he was.

The First Major Clash — The Split City: The Controller chose a coastal megacity. Water access for Blue. Skyscrapers for Indigo. Open sky for White. Tight streets for Purple. He wanted them stretched. The sky cracked with gravitational distortions as Indigo stabilized civilian zones. Blue froze tidal surges mid-rise. Green reinforced collapsing foundations. Grey created barricades. Lavender formed air bridges for evacuation. Pearl guided civilians through smoke using sound pulses. Turquoise infiltrated hostile Elementor cells in shifting forms. Olive shrank collapsing debris. Copper froze micro-seconds to extract trapped families. Scarlet suppressed destabilized death-energy fields from casualties. White evacuated by air. Purple dismantled enemy units in silence. Orange opened rapid-response portals across districts. Amber and Emerald were gone. That absence was felt. And then—the Controller appeared. Above the skyline. Suspended in warped space. "You protect a broken system." Indigo rose to meet him. "You break it." He smiled faintly. "I improve it." He unleashed a citywide pulse. Maroon absorbed as much as he could—veins glowing violently. Yellow enhanced him to withstand the overload. "Keep going!" Yellow shouted. Maroon strained. "I'm not a battery!" Red and Crimson launched synchronized blasts. Black's thunder split the sky. The Controller absorbed, redirected, and returned energy multiplied. Buildings cracked. Civilians screamed. Magenta ran through the chaos, binding structural beams and sealing ruptures with adhesive constructs. "Hold it together!" she yelled. Silver activated foresight. Three seconds. He saw the next shockwave. "Left side, NOW!" Green shifted earth accordingly. They adapted. They pushed back. But this wasn't a duel. It was attrition.

Crimson's Redemption: During the third global strike, the Controller escalated. He created an amplification node—a tower feeding off accumulated Element 6 energy. If it detonated, half the continent would destabilize. Crimson stood before it. Red beside him. "You don't have to do this," Red said. Crimson looked at the tower. "I lost control before." Red's fire burned brighter. "You learned." Crimson exhaled slowly. "No. I just finally understand." He turned to Red. "I'm not leaving another grave." Crimson charged. He didn't explode wildly. He condensed. Focused. His power compressed inward instead of outward. Silver shouted from afar, "Crimson, the feedback will—" Too late. Crimson detonated directly into the core. The blast didn't spread. It imploded. The amplification node collapsed safely inward. The shockwave knocked everyone down. When the smoke cleared—the tower was gone. So was Crimson. Red stood in the crater. Ash falling like snow. "…you idiot." Not angry. Broken. Magenta placed a hand on his shoulder. "He chose control." Red didn't answer.

The Final Controller Battle: The Corps tracked the Controller to a distorted zone outside normal space—an energy nexus formed by accumulated Element 6 residue. Indigo stood at the front. "We end this." The battlefield bent reality. Gravity twisted unpredictably. Time flickered. Copper froze segments mid-collapse. Orange created stable portal anchors. Maroon absorbed waves. Yellow enhanced everyone's endurance. Black unleashed thunder continuously. Blue turned vapor into blades. Green reshaped terrain mid-fight. Purple and White coordinated aerial flanks. Pink matched telekinesis against the Controller directly. Scarlet neutralized death energy surges. Lavender reinforced shifting space with hardened air constructs. Grey shielded under constant pressure. Pearl called out movements in advance. Turquoise shifted into enemy mimic forms to confuse the Controller's projections. Olive resized battlefield sections dynamically. Red burned through containment barriers. It was not clean. It was desperate. Magenta fought near the center, binding fractures in reality itself. The Controller began drawing power from everywhere at once. He grew larger. Brighter. More unstable. "You are fragments," he roared. "I am unity." Indigo screamed back, "You're imbalance." He unleashed a catastrophic pulse aimed at the heart of the team. Magenta saw it first. She ran forward. "NO!" She expanded adhesive constructs outward, forming a dense binding web around the blast. The explosion consumed her position. The team survived. Magenta did not. Silence. Red's fire went white-hot. Pink's telekinesis spiked violently. Indigo's gravity field inverted entirely. Yellow enhanced beyond safe limits. Maroon absorbed energy until he bled from his nose. Black called down lightning so loud the sky tore. Silver activated foresight one final time in the battle. Three seconds. One path. He shouted it. "Now!" All of them attacked simultaneously. Gravity crushed. Thunder split. Fire burned. Water froze. Earth shattered. Energy redirected. Air solidified. Time paused briefly. And the Controller—collapsed. His form fractured. His energy dispersed. The nexus imploded safely. The Controller War ended. But they had lost two more. Crimson. Magenta. The Corps stood at twenty.`
  },
  {
    title: 'Arc VII — The Elementor Purge',
    content: `Peace didn't follow. Fear did. Civilian groups began targeting Elementors quietly. Poisoned food deliveries. Sniper attempts. False emergency calls. Red nearly died in an apartment explosion. Blue was targeted at a water facility. Green uncovered underground sabotage beneath a park. Black intercepted a coordinated lightning trap designed specifically for him.

At Silver's estate, a tense meeting unfolded. "They're scared," Indigo said quietly. "They're trying to erase us," Black replied. Pink looked furious. "Let them try." Silver spoke calmly. "No retaliation." Red clenched his fists. "They killed two of ours." "They're grieving," Magenta would have said. But she wasn't there. Indigo finished it. "We protect them anyway." And they did. Public trust slowly returned. Not through dominance. Through restraint.`
  },
  {
    title: 'Arc VIII — Discovering Evil',
    content: `Years passed. The Controller was gone. But Silver's foresight began failing entirely. Not blocked. Absent. Scarlet detected something deeper than death-energy. Indigo felt gravitational irregularities not tied to Element 6. They gathered at Silver's estate—the same table as before. Night. Storm outside. Silver stood silent. "I can't see beyond this point." Red frowned. "What point?" "After us." Scarlet whispered, "There's something older." Indigo closed her eyes. "I've felt it since I was a child." Pink asked quietly, "Felt what?" Indigo answered. "Opposition." The air shifted. For the first time since the Creation Arc—a presence entered the room. Colder than the Controller. Deeper. Evil. "I grow tired," the voice echoed. Silver's metal form activated instantly. "You." Evil's presence darkened the room. "I was first." Indigo stepped forward. "No. You were balance." Evil responded coldly, "I am correction." The final war had begun.`
  },
  {
    title: 'Arc IX — Killing Evil',
    content: `This was not city-level. Not continental. This was cosmic. Evil did not throw energy. He erased. He attempted to remove existence from sections of reality. Life flickered. Mercy dimmed. Death trembled. The Corps fought in fractured space.

Silver hardened himself completely, reshaping metal around collapsing matter. Black's thunder didn't just strike—it anchored reality. Indigo expanded gravity wells to prevent spatial deletion. Red's fire burned against conceptual void. Pink held collapsing structures in midair. Yellow enhanced continuously, adrenaline locking him into sustained maximum state. Maroon absorbed impossible levels of anti-energy. Blue froze spreading nothingness. Green raised entire continents as shields. Grey reinforced existence with walls of force. Lavender hardened vacuum into barriers. Scarlet redirected erased life-echoes back into matter. White transported civilians across continents. Purple struck at distortion nodes. Orange stabilized portals through collapsing dimensions. Copper froze seconds during reality tears. Pearl navigated through sensory absence. Turquoise shifted into anti-forms to counter Evil's distortions. Olive resized singularities.

They were outmatched. Evil prepared a final annihilation surge aimed at Indigo, Pink, Yellow, Maroon—the core future. Silver saw it. He didn't need foresight. He moved. He hardened beyond his limits. Metal layered over metal. He stood in front. "Not them." The surge hit. Silver shattered. The team screamed. Indigo's gravity inverted violently. Red roared. Black called the loudest thunder the universe had heard. Yellow sustained enhancement indefinitely. Maroon absorbed until he nearly ceased. Together—all remaining heroes attacked simultaneously. Evil fractured. Life surged back. Mercy stabilized. Death closed the rupture. Evil fell. Not erased. Contained. Balance restored.`
  },
  {
    title: 'Arc X — Happily Ever After',
    content: `Life appeared before them. Radiant. Gentle. "You have restored equilibrium." Death stood beside her. Mercy smiled softly. Life offered eternal life. Only Black accepted. Red declined. "I've burned enough." Indigo declined. "I want to live forward." Life looked at Black. "You understand the weight." Black nodded. "I'll stand." Silver revived, Crimson alive again.

Years passed. We see: Red teaching children controlled flame. Pink laughing freely during tournaments. Yellow racing Maroon across open fields. Indigo sitting alone on rooftops in quiet reflection. Blue restoring coral reefs. Green cultivating mountains. Silver alive again, older, smiling softly.

Millions of years later. Black stands in a city alley. A nervous bank robber drops his weapon. Black sighs. "You know I'm immortal, right?" Death appears beside him casually. "You could let him go." Mercy smiles. "He's shaking." Black looks at the robber. "Return the money. Community service. Don't make me call thunder." The robber runs. Death chuckles. "You went from cosmic war to bank patrol." Black smirks. "Promotion." Mercy laughs. The city lights glow peacefully. No fractures. No Anti-All. Just balance. The End.`
  },
];