import React, { useState, useEffect } from 'react';
import { music } from './music.js';
import GameIcon from "./GameIcon.jsx";
import { supabase } from './supabaseClient.js';

export default function SaveCodes({ progress, onImport, onBack }) {
  const [code, setCode] = useState('');
  const [importVal, setImportVal] = useState('');
  const [msg, setMsg] = useState('');

  useEffect(() => { music.play('menu'); return () => music.stop(); }, []);

  const exportCode = async () => {
    try {
      const { data, error } = await supabase.rpc('create_element6_save_code', { p_payload: progress });
      if (error) throw error;
      setCode(data);
      setMsg('Account-bound save code generated. It works only on this Element 6 account.');
    } catch (e) { setMsg('Failed to generate code.'); }
  };

  const applyImport = async () => {
    try {
      const { data: parsed, error } = await supabase.rpc('load_element6_save_code', { p_code: importVal.trim() });
      if (error) throw error;
      if (!parsed.unlockedIds || !Array.isArray(parsed.unlockedIds)) throw new Error('Invalid save');
      onImport(parsed);
      setMsg('Your account save loaded successfully.');
    } catch (e) {
      setMsg(e?.message || 'Invalid save code.');
    }
  };

  return (
    <div className="w-full max-w-2xl flex flex-col gap-4">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-heading text-accent tracking-wider">SAVE CODES</h2>
        <button onClick={onBack} className="px-4 py-2 bg-secondary text-secondary-foreground rounded-lg font-heading text-sm hover:opacity-80"><GameIcon emoji="←" size={14} /> BACK</button>
      </div>

      <div className="bg-card border border-border rounded-xl p-4">
        <h3 className="font-heading text-sm text-primary mb-2">EXPORT YOUR SAVE</h3>
        <p className="text-xs text-muted-foreground font-body mb-2">Generate a code for this account only. It cannot be used by another player.</p>
        <button onClick={exportCode} className="px-4 py-2 bg-accent text-accent-foreground rounded font-heading text-sm hover:opacity-80 mb-2">Generate Code</button>
        {code && (
          <textarea
            readOnly value={code}
            onClick={e => e.target.select()}
            className="w-full h-32 bg-muted text-foreground font-mono text-[10px] p-2 rounded border border-border resize-none"
          />
        )}
      </div>

      <div className="bg-card border border-border rounded-xl p-4">
        <h3 className="font-heading text-sm text-primary mb-2">IMPORT A SAVE</h3>
        <p className="text-xs text-muted-foreground font-body mb-2">Enter a save code generated by this same Element 6 account.</p>
        <textarea
          value={importVal}
          onChange={e => setImportVal(e.target.value)}
          placeholder="Paste save code..."
          className="w-full h-32 bg-muted text-foreground font-mono text-[10px] p-2 rounded border border-border resize-none mb-2"
        />
        <button onClick={applyImport} className="px-4 py-2 bg-primary text-primary-foreground rounded font-heading text-sm hover:opacity-80">Import Save</button>
      </div>

      {msg && <div className="bg-accent/20 border border-accent text-accent rounded-lg px-4 py-2 font-body text-sm">{msg}</div>}
    </div>
  );
}
