-- ELEMENT 6 CLANS
-- Run once in Supabase SQL Editor.
-- This migration is additive: it does not replace existing match/ELO tables.

create extension if not exists pgcrypto;

begin;

create table if not exists public.element6_clans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  name_key text generated always as (lower(regexp_replace(trim(name), '\s+', ' ', 'g'))) stored,
  tag text not null,
  tag_key text generated always as (upper(trim(tag))) stored,
  bio text not null default '',
  icon_url text,
  owner_id uuid not null references auth.users(id) on delete restrict,
  tier smallint not null default 0 check (tier between 0 and 10),
  xp bigint not null default 0 check (xp >= 0),
  tier1_unlocked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists element6_clans_name_key_uq on public.element6_clans(name_key);
create unique index if not exists element6_clans_tag_key_uq on public.element6_clans(tag_key);
create index if not exists element6_clans_tier_idx on public.element6_clans(tier, xp desc);
create index if not exists element6_clans_owner_idx on public.element6_clans(owner_id);

create table if not exists public.element6_clan_members (
  clan_id uuid not null references public.element6_clans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('member','officer','lieutenant','leader')),
  joined_at timestamptz not null default now(),
  primary key (clan_id, user_id)
);
create index if not exists element6_clan_members_user_idx on public.element6_clan_members(user_id);
create index if not exists element6_clan_members_clan_idx on public.element6_clan_members(clan_id, role, joined_at);

create unique index if not exists element6_one_clan_per_user
on public.element6_clan_members(user_id);

create table if not exists public.element6_clan_applications (
  id uuid primary key default gen_random_uuid(),
  clan_id uuid not null references public.element6_clans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null default '',
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);
create unique index if not exists element6_pending_clan_application_uq
on public.element6_clan_applications(clan_id,user_id)
where status='pending';
create index if not exists element6_clan_apps_clan_status_idx
on public.element6_clan_applications(clan_id,status,created_at desc);
create index if not exists element6_clan_apps_user_idx
on public.element6_clan_applications(user_id,status);

create table if not exists public.element6_clan_chat_messages (
  id bigint generated by default as identity primary key,
  clan_id uuid not null references public.element6_clans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);
create index if not exists element6_clan_chat_idx
on public.element6_clan_chat_messages(clan_id,created_at desc);

create table if not exists public.element6_clan_leader_threads (
  id uuid primary key default gen_random_uuid(),
  clan_a_id uuid not null references public.element6_clans(id) on delete cascade,
  clan_b_id uuid not null references public.element6_clans(id) on delete cascade,
  created_at timestamptz not null default now(),
  check (clan_a_id <> clan_b_id)
);
create unique index if not exists element6_leader_thread_pair_uq
on public.element6_clan_leader_threads(
  least(clan_a_id,clan_b_id),
  greatest(clan_a_id,clan_b_id)
);

create table if not exists public.element6_clan_leader_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.element6_clan_leader_threads(id) on delete cascade,
  sender_clan_id uuid not null references public.element6_clans(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);
create index if not exists element6_leader_messages_thread_idx
on public.element6_clan_leader_messages(thread_id,created_at);

create table if not exists public.element6_clan_meetings (
  id uuid primary key default gen_random_uuid(),
  organizer_clan_id uuid not null references public.element6_clans(id) on delete cascade,
  invited_clan_id uuid not null references public.element6_clans(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 100),
  notes text not null default '',
  scheduled_at timestamptz not null,
  status text not null default 'scheduled' check (status in ('scheduled','accepted','declined','cancelled','completed')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (organizer_clan_id <> invited_clan_id)
);
create index if not exists element6_clan_meetings_clan_idx
on public.element6_clan_meetings(organizer_clan_id,scheduled_at);
create index if not exists element6_clan_meetings_invited_idx
on public.element6_clan_meetings(invited_clan_id,scheduled_at);

create table if not exists public.element6_clan_rewards (
  tier smallint primary key check (tier between 1 and 10),
  token_reward integer not null check (token_reward >= 0),
  label text not null
);

insert into public.element6_clan_rewards(tier,token_reward,label) values
(1,500,'Tier 1 reward'),
(2,1000,'Tier 2 reward'),
(3,1500,'Tier 3 reward'),
(4,2500,'Tier 4 reward'),
(5,3500,'Tier 5 reward'),
(6,5000,'Tier 6 reward'),
(7,7000,'Tier 7 reward'),
(8,9000,'Tier 8 reward'),
(9,12000,'Tier 9 reward'),
(10,20000,'Tier 10 reward')
on conflict(tier) do update set token_reward=excluded.token_reward,label=excluded.label;

create table if not exists public.element6_clan_reward_claims (
  clan_id uuid not null references public.element6_clans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  tier smallint not null references public.element6_clan_rewards(tier),
  claimed_at timestamptz not null default now(),
  primary key(clan_id,user_id,tier)
);

create table if not exists public.element6_clan_activity_events (
  id bigint generated by default as identity primary key,
  clan_id uuid not null references public.element6_clans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  xp integer not null default 0 check (xp >= 0),
  source_match_id text,
  created_at timestamptz not null default now()
);
create index if not exists element6_clan_activity_clan_idx
on public.element6_clan_activity_events(clan_id,created_at desc);
create unique index if not exists element6_clan_activity_source_uq
on public.element6_clan_activity_events(clan_id,user_id,event_key,source_match_id)
where source_match_id is not null;

-- Tier 0 -> Tier 1 happens on the first qualifying match/event.
-- Later tiers require both activity XP and minimum elapsed clan age.
create or replace function public.element6_clan_required_xp(p_tier smallint)
returns bigint language sql immutable as $$
  select case p_tier
    when 0 then 1
    when 1 then 75
    when 2 then 250
    when 3 then 550
    when 4 then 1000
    when 5 then 1600
    when 6 then 2400
    when 7 then 3400
    when 8 then 4700
    when 9 then 6500
    else 0
  end;
$$;

create or replace function public.element6_clan_min_days_for_tier(p_tier smallint)
returns integer language sql immutable as $$
  select case p_tier
    when 1 then 0
    when 2 then 7
    when 3 then 21
    when 4 then 45
    when 5 then 75
    when 6 then 110
    when 7 then 150
    when 8 then 200
    when 9 then 270
    when 10 then 365
    else 0
  end;
$$;

-- IMPORTANT: this is the secure server-side hook the game should call
-- after a qualifying match is genuinely completed. The browser cannot
-- directly promote a clan or award XP through the table policies.
create or replace function public.element6_record_clan_activity(
  p_user_id uuid,
  p_event_key text,
  p_xp integer,
  p_source_match_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_clan public.element6_clans%rowtype;
  v_member boolean;
  v_new_tier smallint;
begin
  if p_user_id is null then raise exception 'Missing user'; end if;
  if p_xp < 0 then raise exception 'Invalid XP'; end if;

  select exists(
    select 1 from public.element6_clan_members
    where clan_id is not null and user_id=p_user_id
  ) into v_member;

  if not v_member then
    return jsonb_build_object('recorded',false,'reason','not_in_clan');
  end if;

  select c.* into v_clan
  from public.element6_clans c
  join public.element6_clan_members m on m.clan_id=c.id
  where m.user_id=p_user_id
  for update;

  if v_clan.id is null then
    return jsonb_build_object('recorded',false,'reason','not_in_clan');
  end if;

  if p_source_match_id is not null then
    insert into public.element6_clan_activity_events(clan_id,user_id,event_key,xp,source_match_id)
    values(v_clan.id,p_user_id,p_event_key,greatest(0,p_xp),p_source_match_id)
    on conflict do nothing;
  else
    insert into public.element6_clan_activity_events(clan_id,user_id,event_key,xp)
    values(v_clan.id,p_user_id,p_event_key,greatest(0,p_xp));
  end if;

  if p_source_match_id is not null and not found then
    return jsonb_build_object('recorded',false,'reason','already_recorded','tier',v_clan.tier,'xp',v_clan.xp);
  end if;

  update public.element6_clans
  set xp=xp+greatest(0,p_xp),
      tier=greatest(tier,
        case
          when tier=0 then 1
          else tier
        end
      ),
      tier1_unlocked_at=coalesce(tier1_unlocked_at,now()),
      updated_at=now()
  where id=v_clan.id;

  select * into v_clan from public.element6_clans where id=v_clan.id for update;

  v_new_tier:=v_clan.tier;
  while v_new_tier < 10
    and v_clan.xp >= public.element6_clan_required_xp(v_new_tier)
    and now() >= v_clan.created_at + make_interval(days => public.element6_clan_min_days_for_tier(v_new_tier+1))
  loop
    v_new_tier:=v_new_tier+1;
  end loop;

  if v_new_tier <> v_clan.tier then
    update public.element6_clans
    set tier=v_new_tier, updated_at=now()
    where id=v_clan.id;
  end if;

  return jsonb_build_object('recorded',true,'clan_id',v_clan.id,'tier',v_new_tier,'xp',v_clan.xp);
end;
$$;

revoke all on function public.element6_record_clan_activity(uuid,text,integer,text) from public,anon;
grant execute on function public.element6_record_clan_activity(uuid,text,integer,text) to authenticated;

-- One secure read model for the clan member ELO screen.
create or replace function public.element6_get_clan_member_elo(p_clan_id uuid)
returns table(
  user_id uuid,
  username text,
  role text,
  ranked_rating integer,
  ranked_wins integer,
  ranked_losses integer,
  ranked_matches integer,
  soccer_rating integer,
  soccer_wins integer,
  soccer_losses integer,
  soccer_matches integer,
  volleyball_rating integer,
  volleyball_wins integer,
  volleyball_losses integer,
  volleyball_matches integer,
  dodgeball_rating integer,
  dodgeball_wins integer,
  dodgeball_losses integer,
  dodgeball_matches integer
)
language sql
security definer
set search_path=public
as $$
  select
    m.user_id,
    coalesce(pp.username,'Player'),
    m.role,
    coalesce(rr.rating,1000),
    coalesce(rr.wins,0),
    coalesce(rr.losses,0),
    coalesce(rr.matches_played,0),
    coalesce(soc.rating,1000),
    coalesce(soc.wins,0),
    coalesce(soc.losses,0),
    coalesce(soc.matches_played,0),
    coalesce(vb.rating,1000),
    coalesce(vb.wins,0),
    coalesce(vb.losses,0),
    coalesce(vb.matches_played,0),
    coalesce(db.rating,1000),
    coalesce(db.wins,0),
    coalesce(db.losses,0),
    coalesce(db.matches_played,0)
  from public.element6_clan_members m
  left join public.player_profiles pp on pp.user_id=m.user_id
  left join public.ranked_ratings rr on rr.user_id=m.user_id
  left join public.online_sport_ratings soc on soc.user_id=m.user_id and soc.mode='soccer_ranked'
  left join public.online_sport_ratings vb on vb.user_id=m.user_id and vb.mode='volleyball_1v1_ranked'
  left join public.online_sport_ratings db on db.user_id=m.user_id and db.mode='dodgeball_ranked'
  where m.clan_id=p_clan_id
    and exists(
      select 1 from public.element6_clan_members me
      where me.clan_id=p_clan_id and me.user_id=auth.uid()
    )
  order by m.role='leader' desc, m.joined_at, pp.username;
$$;

revoke all on function public.element6_get_clan_member_elo(uuid) from public,anon;
grant execute on function public.element6_get_clan_member_elo(uuid) to authenticated;

-- Secure RPCs for membership management.
create or replace function public.element6_create_clan(
  p_name text,p_tag text,p_bio text default '',p_icon_url text default null
)
returns public.element6_clans
language plpgsql security definer set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_clan public.element6_clans;
begin
  if v_user is null then raise exception 'Sign in first'; end if;
  if exists(select 1 from public.element6_clan_members where user_id=v_user) then raise exception 'You are already in a clan'; end if;
  if char_length(trim(p_name)) not between 3 and 24 then raise exception 'Clan name must be 3-24 characters'; end if;
  if p_tag is null or trim(p_tag) !~ '^[A-Za-z0-9]{2,6}$' then raise exception 'Clan tag must be 2-6 letters or numbers'; end if;

  -- Token deduction is intentionally delegated to the existing account economy
  -- through the client integration callback. This RPC only creates the clan.
  insert into public.element6_clans(name,tag,bio,icon_url,owner_id)
  values(trim(p_name),upper(trim(p_tag)),left(coalesce(p_bio,''),500),p_icon_url,v_user)
  returning * into v_clan;

  insert into public.element6_clan_members(clan_id,user_id,role)
  values(v_clan.id,v_user,'leader');

  return v_clan;
end;
$$;
revoke all on function public.element6_create_clan(text,text,text,text) from public,anon;
grant execute on function public.element6_create_clan(text,text,text,text) to authenticated;

create or replace function public.element6_apply_to_clan(p_clan_id uuid,p_message text default '')
returns public.element6_clan_applications
language plpgsql security definer set search_path=public
as $$
declare v_user uuid:=auth.uid(); r public.element6_clan_applications;
begin
  if v_user is null then raise exception 'Sign in first'; end if;
  if exists(select 1 from public.element6_clan_members where user_id=v_user) then raise exception 'Leave your current clan first'; end if;
  if not exists(select 1 from public.element6_clans where id=p_clan_id) then raise exception 'Clan not found'; end if;
  insert into public.element6_clan_applications(clan_id,user_id,message)
  values(p_clan_id,v_user,left(coalesce(p_message,''),300))
  returning * into r;
  return r;
end;
$$;
revoke all on function public.element6_apply_to_clan(uuid,text) from public,anon;
grant execute on function public.element6_apply_to_clan(uuid,text) to authenticated;

create or replace function public.element6_review_clan_application(p_application_id uuid,p_approve boolean)
returns public.element6_clan_applications
language plpgsql security definer set search_path=public
as $$
declare
  a public.element6_clan_applications;
  v_user uuid:=auth.uid();
  v_role text;
begin
  select * into a from public.element6_clan_applications where id=p_application_id for update;
  if a.id is null then raise exception 'Application not found'; end if;
  select role into v_role from public.element6_clan_members where clan_id=a.clan_id and user_id=v_user;
  if v_role <> 'leader' then raise exception 'Only the clan leader can approve applications'; end if;
  if a.status <> 'pending' then raise exception 'Application already reviewed'; end if;

  if p_approve then
    if exists(select 1 from public.element6_clan_members where user_id=a.user_id) then raise exception 'Player is already in a clan'; end if;
    insert into public.element6_clan_members(clan_id,user_id,role) values(a.clan_id,a.user_id,'member');
    update public.element6_clan_applications set status='approved',reviewed_at=now(),reviewed_by=v_user where id=a.id;
  else
    update public.element6_clan_applications set status='rejected',reviewed_at=now(),reviewed_by=v_user where id=a.id;
  end if;
  select * into a from public.element6_clan_applications where id=a.id;
  return a;
end;
$$;
revoke all on function public.element6_review_clan_application(uuid,boolean) from public,anon;
grant execute on function public.element6_review_clan_application(uuid,boolean) to authenticated;

create or replace function public.element6_leave_clan()
returns void language plpgsql security definer set search_path=public
as $$
declare v_user uuid:=auth.uid(); v_role text;
begin
  select role into v_role from public.element6_clan_members where user_id=v_user;
  if v_role is null then raise exception 'You are not in a clan'; end if;
  if v_role='leader' then raise exception 'Leader must transfer ownership or disband the clan'; end if;
  delete from public.element6_clan_members where user_id=v_user;
end;
$$;
revoke all on function public.element6_leave_clan() from public,anon;
grant execute on function public.element6_leave_clan() to authenticated;

create or replace function public.element6_transfer_clan_ownership(p_new_owner uuid)
returns void language plpgsql security definer set search_path=public
as $$
declare v_user uuid:=auth.uid(); v_clan uuid;
begin
  select clan_id into v_clan from public.element6_clan_members where user_id=v_user and role='leader';
  if v_clan is null then raise exception 'Only the leader can transfer ownership'; end if;
  if not exists(select 1 from public.element6_clan_members where clan_id=v_clan and user_id=p_new_owner) then raise exception 'New owner must be a clan member'; end if;
  update public.element6_clan_members set role='lieutenant' where clan_id=v_clan and user_id=v_user;
  update public.element6_clan_members set role='leader' where clan_id=v_clan and user_id=p_new_owner;
  update public.element6_clans set owner_id=p_new_owner,updated_at=now() where id=v_clan;
end;
$$;
revoke all on function public.element6_transfer_clan_ownership(uuid) from public,anon;
grant execute on function public.element6_transfer_clan_ownership(uuid) to authenticated;

create or replace function public.element6_disband_clan()
returns void language plpgsql security definer set search_path=public
as $$
declare v_user uuid:=auth.uid(); v_clan uuid;
begin
  select clan_id into v_clan from public.element6_clan_members where user_id=v_user and role='leader';
  if v_clan is null then raise exception 'Only the leader can disband the clan'; end if;
  delete from public.element6_clans where id=v_clan;
end;
$$;
revoke all on function public.element6_disband_clan() from public,anon;
grant execute on function public.element6_disband_clan() to authenticated;

create or replace function public.element6_set_clan_member_role(p_member uuid,p_role text)
returns void language plpgsql security definer set search_path=public
as $$
declare v_user uuid; v_clan uuid;
begin
  v_user:=auth.uid();
  select clan_id into v_clan from public.element6_clan_members where user_id=v_user and role='leader';
  if v_clan is null then raise exception 'Only leader'; end if;
  if p_role not in ('member','officer','lieutenant') then raise exception 'Invalid role'; end if;
  if p_member=v_user then raise exception 'Leader cannot demote self with this action'; end if;
  if not exists(select 1 from public.element6_clan_members where clan_id=v_clan and user_id=p_member) then raise exception 'Member not found'; end if;
  update public.element6_clan_members set role=p_role where clan_id=v_clan and user_id=p_member;
end;
$$;
revoke all on function public.element6_set_clan_member_role(uuid,text) from public,anon;
grant execute on function public.element6_set_clan_member_role(uuid,text) to authenticated;


create or replace function public.element6_update_clan(
  p_name text default null,
  p_tag text default null,
  p_bio text default null,
  p_icon_url text default null
)
returns public.element6_clans
language plpgsql security definer set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_clan uuid;
  v_row public.element6_clans;
begin
  select clan_id into v_clan
  from public.element6_clan_members
  where user_id=v_user and role='leader';
  if v_clan is null then raise exception 'Only the leader can edit clan settings'; end if;

  update public.element6_clans
  set name=coalesce(nullif(trim(p_name),''),name),
      tag=coalesce(nullif(upper(trim(p_tag)),''),tag),
      bio=coalesce(left(p_bio,500),bio),
      icon_url=coalesce(p_icon_url,icon_url),
      updated_at=now()
  where id=v_clan
  returning * into v_row;

  return v_row;
end;
$$;
revoke all on function public.element6_update_clan(text,text,text,text) from public,anon;
grant execute on function public.element6_update_clan(text,text,text,text) to authenticated;

create or replace function public.element6_get_or_create_leader_thread(p_other_clan uuid)
returns public.element6_clan_leader_threads
language plpgsql security definer set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_my_clan uuid;
  v_row public.element6_clan_leader_threads;
  a uuid;
  b uuid;
begin
  select clan_id into v_my_clan from public.element6_clan_members
  where user_id=v_user and role='leader';
  if v_my_clan is null then raise exception 'Only clan leaders can use leader chat'; end if;
  if not exists(select 1 from public.element6_clans where id=p_other_clan) then raise exception 'Clan not found'; end if;
  if v_my_clan=p_other_clan then raise exception 'Choose another clan'; end if;

  a:=least(v_my_clan,p_other_clan);
  b:=greatest(v_my_clan,p_other_clan);

  select * into v_row from public.element6_clan_leader_threads
  where clan_a_id=a and clan_b_id=b
  limit 1;

  if v_row.id is null then
    insert into public.element6_clan_leader_threads(clan_a_id,clan_b_id)
    values(a,b)
    on conflict do nothing;
    select * into v_row from public.element6_clan_leader_threads
    where clan_a_id=a and clan_b_id=b
    limit 1;
  end if;
  return v_row;
end;
$$;
revoke all on function public.element6_get_or_create_leader_thread(uuid) from public,anon;
grant execute on function public.element6_get_or_create_leader_thread(uuid) to authenticated;

create or replace function public.element6_claim_clan_reward(p_tier smallint)
returns integer
language plpgsql security definer set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_clan uuid;
  v_reward integer;
begin
  select clan_id into v_clan from public.element6_clan_members where user_id=v_user;
  if v_clan is null then raise exception 'Not in a clan'; end if;
  if not exists(select 1 from public.element6_clans where id=v_clan and tier>=p_tier) then raise exception 'Tier not reached'; end if;
  select token_reward into v_reward from public.element6_clan_rewards where tier=p_tier;
  if v_reward is null then raise exception 'Reward not found'; end if;

  insert into public.element6_clan_reward_claims(clan_id,user_id,tier)
  values(v_clan,v_user,p_tier)
  on conflict do nothing;

  if not found then raise exception 'Reward already claimed'; end if;
  return v_reward;
end;
$$;
revoke all on function public.element6_claim_clan_reward(smallint) from public,anon;
grant execute on function public.element6_claim_clan_reward(smallint) to authenticated;

create or replace function public.element6_set_clan_meeting_status(p_meeting_id uuid,p_status text)
returns void
language plpgsql security definer set search_path=public
as $$
declare
  v_user uuid:=auth.uid();
  v_clan uuid;
begin
  if p_status not in ('accepted','declined','cancelled','completed') then raise exception 'Invalid meeting status'; end if;
  select clan_id into v_clan from public.element6_clan_members where user_id=v_user and role='leader';
  if v_clan is null then raise exception 'Only leaders can manage meetings'; end if;
  update public.element6_clan_meetings
  set status=p_status,updated_at=now()
  where id=p_meeting_id
    and (organizer_clan_id=v_clan or invited_clan_id=v_clan);
end;
$$;
revoke all on function public.element6_set_clan_meeting_status(uuid,text) from public,anon;
grant execute on function public.element6_set_clan_meeting_status(uuid,text) to authenticated;

drop policy if exists element6_leader_threads_insert on public.element6_clan_leader_threads;
create policy element6_leader_threads_insert on public.element6_clan_leader_threads
for insert to authenticated
with check (
  exists(select 1 from public.element6_clan_members m where m.user_id=auth.uid() and m.role='leader' and m.clan_id in (clan_a_id,clan_b_id))
);

-- RLS
alter table public.element6_clans enable row level security;
alter table public.element6_clan_members enable row level security;
alter table public.element6_clan_applications enable row level security;
alter table public.element6_clan_chat_messages enable row level security;
alter table public.element6_clan_leader_threads enable row level security;
alter table public.element6_clan_leader_messages enable row level security;
alter table public.element6_clan_meetings enable row level security;
alter table public.element6_clan_rewards enable row level security;
alter table public.element6_clan_reward_claims enable row level security;
alter table public.element6_clan_activity_events enable row level security;

drop policy if exists element6_clans_browse on public.element6_clans;
create policy element6_clans_browse on public.element6_clans for select to authenticated using (true);

drop policy if exists element6_members_browse on public.element6_clan_members;
create policy element6_members_browse on public.element6_clan_members for select to authenticated using (true);

drop policy if exists element6_apps_own_or_leader on public.element6_clan_applications;
create policy element6_apps_own_or_leader on public.element6_clan_applications for select to authenticated
using (
  user_id=auth.uid()
  or exists(select 1 from public.element6_clan_members m where m.clan_id=element6_clan_applications.clan_id and m.user_id=auth.uid() and m.role='leader')
);

drop policy if exists element6_chat_members on public.element6_clan_chat_messages;
create policy element6_chat_members on public.element6_clan_chat_messages for select to authenticated
using (exists(select 1 from public.element6_clan_members m where m.clan_id=element6_clan_chat_messages.clan_id and m.user_id=auth.uid()));
create policy element6_chat_insert_members on public.element6_clan_chat_messages for insert to authenticated
with check (user_id=auth.uid() and exists(select 1 from public.element6_clan_members m where m.clan_id=element6_clan_chat_messages.clan_id and m.user_id=auth.uid()));

drop policy if exists element6_rewards_read on public.element6_clan_rewards;
create policy element6_rewards_read on public.element6_clan_rewards for select to authenticated using (true);

drop policy if exists element6_meetings_members on public.element6_clan_meetings;
create policy element6_meetings_members on public.element6_clan_meetings for select to authenticated
using (
 exists(select 1 from public.element6_clan_members m where m.clan_id in (organizer_clan_id,invited_clan_id) and m.user_id=auth.uid())
);

drop policy if exists element6_leader_threads_leaders on public.element6_clan_leader_threads;
create policy element6_leader_threads_leaders on public.element6_clan_leader_threads for select to authenticated
using (
 exists(select 1 from public.element6_clan_members m where m.clan_id in (clan_a_id,clan_b_id) and m.user_id=auth.uid() and m.role='leader')
);

drop policy if exists element6_leader_messages_leaders on public.element6_clan_leader_messages;
create policy element6_leader_messages_leaders on public.element6_clan_leader_messages for select to authenticated
using (
 exists(
   select 1 from public.element6_clan_leader_threads t
   join public.element6_clan_members m on m.clan_id in (t.clan_a_id,t.clan_b_id)
   where t.id=thread_id and m.user_id=auth.uid() and m.role='leader'
 )
);
create policy element6_leader_messages_insert on public.element6_clan_leader_messages for insert to authenticated
with check (
 sender_user_id=auth.uid()
 and exists(
   select 1 from public.element6_clan_members m
   join public.element6_clan_leader_threads t on t.id=thread_id
   where m.user_id=auth.uid() and m.role='leader' and m.clan_id in (t.clan_a_id,t.clan_b_id)
 )
);

drop policy if exists element6_meetings_insert_leader on public.element6_clan_meetings;
create policy element6_meetings_insert_leader on public.element6_clan_meetings
for insert to authenticated
with check (
  created_by=auth.uid()
  and exists(
    select 1 from public.element6_clan_members m
    where m.user_id=auth.uid() and m.role='leader' and m.clan_id=organizer_clan_id
  )
);

-- Public members may not update clan tables directly; all mutation paths go through RPCs.
revoke insert,update,delete on public.element6_clans from authenticated;
revoke insert,update,delete on public.element6_clan_members from authenticated;
revoke insert,update,delete on public.element6_clan_applications from authenticated;
revoke update,delete on public.element6_clan_chat_messages from authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='element6_clan_chat_messages')
    then alter publication supabase_realtime add table public.element6_clan_chat_messages; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='element6_clan_applications')
    then alter publication supabase_realtime add table public.element6_clan_applications; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='element6_clan_meetings')
    then alter publication supabase_realtime add table public.element6_clan_meetings; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='element6_clan_leader_messages')
    then alter publication supabase_realtime add table public.element6_clan_leader_messages; end if;
end $$;

commit;
