-- ELEMENT 6 - CLAN SOCIAL + MEMBER/ELO FIX
-- Additive and safe to rerun.
-- Run this AFTER the existing clan SQL and after the Ranked/Online Sports ELO tables exist.
-- Fixes:
--   1. Clan chat read/write policies + realtime publication.
--   2. Clan application read/write policies + realtime publication.
--   3. Member list read model with usernames (avoids broken nested PostgREST relations).
--   4. Application read model with usernames for leaders.
--   5. Clan chat read model with usernames for members.
--   6. Clan member ELO read model for Ranked/Soccer/Volleyball/Dodgeball.

begin;

create table if not exists public.element6_clan_applications (
  id uuid primary key default gen_random_uuid(),
  clan_id uuid not null references public.element6_clans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null default '',
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);
create unique index if not exists element6_pending_clan_application_uq
  on public.element6_clan_applications(clan_id,user_id) where status='pending';
create index if not exists element6_clan_apps_clan_status_idx
  on public.element6_clan_applications(clan_id,status,created_at desc);
create index if not exists element6_clan_apps_user_idx
  on public.element6_clan_applications(user_id,status);

create table if not exists public.element6_clan_chat_messages (
  id bigint generated by default as identity primary key,
  clan_id uuid not null references public.element6_clans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);
create index if not exists element6_clan_chat_idx
  on public.element6_clan_chat_messages(clan_id,created_at desc);

alter table public.element6_clan_members enable row level security;
alter table public.element6_clan_applications enable row level security;
alter table public.element6_clan_chat_messages enable row level security;

drop policy if exists element6_members_browse on public.element6_clan_members;
create policy element6_members_browse on public.element6_clan_members
for select to authenticated using (true);

drop policy if exists element6_apps_own_or_leader on public.element6_clan_applications;
create policy element6_apps_own_or_leader on public.element6_clan_applications
for select to authenticated using (
  user_id = auth.uid()
  or exists (
    select 1 from public.element6_clan_members m
    where m.clan_id = element6_clan_applications.clan_id
      and m.user_id = auth.uid()
      and m.role = 'leader'
  )
);

drop policy if exists element6_chat_members on public.element6_clan_chat_messages;
create policy element6_chat_members on public.element6_clan_chat_messages
for select to authenticated using (
  exists (
    select 1 from public.element6_clan_members m
    where m.clan_id = element6_clan_chat_messages.clan_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists element6_chat_insert_members on public.element6_clan_chat_messages;
create policy element6_chat_insert_members on public.element6_clan_chat_messages
for insert to authenticated with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.element6_clan_members m
    where m.clan_id = element6_clan_chat_messages.clan_id
      and m.user_id = auth.uid()
  )
);

-- Browser only needs read access. Mutations stay behind the existing RPCs.
grant select on public.element6_clan_members to authenticated;
grant select on public.element6_clan_applications to authenticated;
grant select,insert on public.element6_clan_chat_messages to authenticated;
revoke update,delete on public.element6_clan_chat_messages from authenticated;

-- Secure member list read model. This joins player_profiles on user_id inside SQL,
-- so the browser does not depend on a PostgREST relationship between auth.users and player_profiles.
drop function if exists public.element6_get_clan_members(uuid);
create function public.element6_get_clan_members(p_clan_id uuid)
returns table(user_id uuid, username text, role text, joined_at timestamptz)
language sql
security definer
set search_path=''
as $$
  select
    m.user_id,
    coalesce(p.username,'Player') as username,
    m.role,
    m.joined_at
  from public.element6_clan_members m
  left join public.player_profiles p on p.user_id=m.user_id
  where m.clan_id=p_clan_id
    and exists (
      select 1 from public.element6_clan_members me
      where me.clan_id=p_clan_id and me.user_id=auth.uid()
    )
  order by case when m.role='leader' then 0 when m.role='lieutenant' then 1 when m.role='officer' then 2 else 3 end,
           m.joined_at,
           coalesce(p.username,'Player');
$$;
revoke all on function public.element6_get_clan_members(uuid) from public,anon;
grant execute on function public.element6_get_clan_members(uuid) to authenticated;

-- Secure pending-application read model. Only the clan leader can read it.
drop function if exists public.element6_get_clan_applications(uuid);
create function public.element6_get_clan_applications(p_clan_id uuid)
returns table(id uuid,user_id uuid,username text,message text,status text,created_at timestamptz)
language sql
security definer
set search_path=''
as $$
  select
    a.id,
    a.user_id,
    coalesce(p.username,'Player') as username,
    a.message,
    a.status,
    a.created_at
  from public.element6_clan_applications a
  left join public.player_profiles p on p.user_id=a.user_id
  where a.clan_id=p_clan_id
    and a.status='pending'
    and exists (
      select 1 from public.element6_clan_members m
      where m.clan_id=p_clan_id and m.user_id=auth.uid() and m.role='leader'
    )
  order by a.created_at;
$$;
revoke all on function public.element6_get_clan_applications(uuid) from public,anon;
grant execute on function public.element6_get_clan_applications(uuid) to authenticated;

-- Secure clan chat read model with usernames.
drop function if exists public.element6_get_clan_chat(uuid);
create function public.element6_get_clan_chat(p_clan_id uuid)
returns table(id bigint,clan_id uuid,user_id uuid,username text,body text,created_at timestamptz)
language sql
security definer
set search_path=''
as $$
  select
    c.id,
    c.clan_id,
    c.user_id,
    coalesce(p.username,'Player') as username,
    c.body,
    c.created_at
  from public.element6_clan_chat_messages c
  left join public.player_profiles p on p.user_id=c.user_id
  where c.clan_id=p_clan_id
    and exists (
      select 1 from public.element6_clan_members m
      where m.clan_id=p_clan_id and m.user_id=auth.uid()
    )
  order by c.created_at desc
  limit 100;
$$;
revoke all on function public.element6_get_clan_chat(uuid) from public,anon;
grant execute on function public.element6_get_clan_chat(uuid) to authenticated;

-- Rebuild the member ELO RPC with a pinned search_path and the same four modes used by the game.
drop function if exists public.element6_get_clan_member_elo(uuid);
create function public.element6_get_clan_member_elo(p_clan_id uuid)
returns table(
  user_id uuid,
  username text,
  role text,
  ranked_rating integer,
  ranked_wins integer,
  ranked_losses integer,
  ranked_matches integer,
  soccer_rating integer,
  soccer_wins integer,
  soccer_losses integer,
  soccer_matches integer,
  volleyball_rating integer,
  volleyball_wins integer,
  volleyball_losses integer,
  volleyball_matches integer,
  dodgeball_rating integer,
  dodgeball_wins integer,
  dodgeball_losses integer,
  dodgeball_matches integer
)
language sql
security definer
set search_path=''
as $$
  select
    m.user_id,
    coalesce(pp.username,'Player') as username,
    m.role,
    coalesce(rr.rating,1000),
    coalesce(rr.wins,0),
    coalesce(rr.losses,0),
    coalesce(rr.matches_played,0),
    coalesce(soc.rating,1000),
    coalesce(soc.wins,0),
    coalesce(soc.losses,0),
    coalesce(soc.matches_played,0),
    coalesce(vb.rating,1000),
    coalesce(vb.wins,0),
    coalesce(vb.losses,0),
    coalesce(vb.matches_played,0),
    coalesce(db.rating,1000),
    coalesce(db.wins,0),
    coalesce(db.losses,0),
    coalesce(db.matches_played,0)
  from public.element6_clan_members m
  left join public.player_profiles pp on pp.user_id=m.user_id
  left join public.ranked_ratings rr on rr.user_id=m.user_id
  left join public.online_sport_ratings soc on soc.user_id=m.user_id and soc.mode='soccer_ranked'
  left join public.online_sport_ratings vb on vb.user_id=m.user_id and vb.mode='volleyball_1v1_ranked'
  left join public.online_sport_ratings db on db.user_id=m.user_id and db.mode='dodgeball_ranked'
  where m.clan_id=p_clan_id
    and exists (
      select 1 from public.element6_clan_members me
      where me.clan_id=p_clan_id and me.user_id=auth.uid()
    )
  order by case when m.role='leader' then 0 when m.role='lieutenant' then 1 when m.role='officer' then 2 else 3 end,
           m.joined_at,
           pp.username;
$$;
revoke all on function public.element6_get_clan_member_elo(uuid) from public,anon;
grant execute on function public.element6_get_clan_member_elo(uuid) to authenticated;

-- Realtime for chat/applications.
do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='element6_clan_chat_messages') then
      alter publication supabase_realtime add table public.element6_clan_chat_messages;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='element6_clan_applications') then
      alter publication supabase_realtime add table public.element6_clan_applications;
    end if;
  end if;
end $$;

commit;
